WorldOfDarknessXIII/World-of-Darkness-13

- code/modules/vtmb/vampire_clane/tzimisce.dm
tzimisce strong now :)
freaky fleshcrafters no longer bitch-made
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
> big ol honkin tzimisce warform buff

- code/modules/vtmb/jobs.dm
Bug fix.
Bug fix.
cl:
fix: Citizens now spawn with items in their backpacks again. Fix is slightly crude but else function wasn't working. Shrug.
/:cl:
> Citizen_backpack_fix

- code/modules/client/preferences.dm
10 character slots. Let people play what they want as.
More variety. More options. Good stuff.
:cl:
add: 10 character slots.
/:cl:
> extra_save_slots

- code/modules/client/preferences.dm
- code/modules/vtmb/archetypes.dm
- code/modules/vtmb/artifacts.dm
fixed leftover artifact spawn - well - artifacts
people won't ask the chantry to identify invisible items anymore
:cl:
tweak: refactored way that artifact spawns are calculated at initialization to delete old artifacts that weren't actually spawned based on their probability
/:cl:
> Unfucky-wuckied the artifact spawn qdel

- tgstation.dme
it fixes lockpicking and z-levels
just fucking merge it
> Fix TGStation.dme

- code/modules/ziggers/food.dm
Adds a lockpick to the black market that costs 50 dollars.
Makes it easier to utilize lockpicking skill.
:cl:
tweak: lockpick is now available in black market
/:cl:
> lockpick_black_market

- code/modules/vtmb/jobs.dm
- code/modules/vtmb/werewolf_species.dm
Disables werewolves from the game. Jobs or as choice and all. Black Spiral Dancers are still in.
We planned this already. Garou just don't have a place right now - and all every garou player is doing is hanging out with kindred all round, which is deeply lore inaccurate.
:cl:
del: Removed the ability to play as a non-antagonistic werewolf.
/:cl:
> werewolf_disable

- code/modules/vtmb/kindred_species.dm
- strings/tips.txt
Literally just some word changes in flavor and new more fitting tips.
Makes a better reading and more accurate tips.
:cl:
tweak: altered some flavor texts
/:cl:
> Mild flavor and text changes.

- code/modules/vtmb/electronics/computers/computer.dm
Phones now inform about the Prince's announcements being made by beeping "New Announcement!"
People won't forget about announcements if they are made.
:cl:
add: phones now beep when prince makes an announcement
/:cl:
> phones_inform_of_announcement

- code/modules/vtmb/vampire_clane/baali.dm
- code/modules/vtmb/vampire_clane/banu_haqim.dm
- code/modules/vtmb/vampire_clane/bruja.dm
- code/modules/vtmb/vampire_clane/doc.dm
- code/modules/vtmb/vampire_clane/gangrel.dm
- code/modules/vtmb/vampire_clane/giovanni.dm
- code/modules/vtmb/vampire_clane/lasombra.dm
- code/modules/vtmb/vampire_clane/malkavian.dm
- code/modules/vtmb/vampire_clane/ministry.dm
- code/modules/vtmb/vampire_clane/nosferatu.dm
- code/modules/vtmb/vampire_clane/old_clan_tzimisce.dm
- code/modules/vtmb/vampire_clane/salubri.dm
- code/modules/vtmb/vampire_clane/toreador.dm
- code/modules/vtmb/vampire_clane/tremere.dm
- code/modules/vtmb/vampire_clane/ventrue.dm
- code/modules/vtmb/werewolf/auspice.dm
- code/modules/vtmb/werewolf/spiral_antag.dm
I brought the indentation in clan/tribes files to our standards :)
Bad indentation makes my brain itch, good indentation scratches my brain
:cl:
code: Made indentation in clan/tribe files saner.
/:cl:
> Indent sanitisation in both werewolf tribes and kindred clans

- code/controllers/subsystem/job.dm
- code/modules/client/preferences.dm
- code/modules/jobs/job_types/_job.dm
- code/modules/mob/dead/new_player/new_player.dm
- code/modules/vtmb/jobs.dm
Removes some remnants of code allowing for children left by old codebase owners.
removes chance of confusion from code divers thinking that we even remotely entertain the idea of minors being allowed on the server. (Even though it's been mechanically impossible for ages. Why didn't you just remove this flav?)
:cl:
del: Removed vestigial age allowed code
/:cl:
> Let's get that right on up out of there

- code/modules/wod13/doorcode.dm
If the warehouse is independent, they can afford to get new locks.
It forces the baron to actually aggress the warehouse, rather than just walk in all willy-nilly, actually creating conflict, as opposed to annoyance.
:cl:
fix: fixed the access issues at the warehouse
/:cl:
> Fixing baron having access to warehouse

- code/modules/wod13/fishing.dm
- code/modules/wod13/lombard.dm
Fishing is a lot better and ready to be set up to work with a survival skill later on. Prices of fish have been increased also.
It will make a feature that has been practically ignored, usable again, and humanity-following kindred have a money-making activity.
:cl:
balance: rebalanced fishing and it's profits
/:cl:
> Fishing buff

- code/game/objects/structures/guillotine.dm
- code/modules/wod13/onyxcombat.dm
Removes extra torpor for being killed by guillotine or just normally. Might not affect getting wighted and contract'd.
Will make the players less fearful to roleplay or endanger themselves, won't demotivate people with exp losses.
:cl:
tweak: you can no longer be torpored by normal death or the guillotine
/:cl:
> Removes some death consequences

- code/modules/mob/living/carbon/human/species.dm
- code/modules/wod13/quirks.dm
Makes it so the fly up button actually moves you up. Better that button does something than be removed, it's in a nicer place than verbs.
It is a fix.
:cl:
fix: the fly up button now works properly
/:cl:
> Fly up fix

- code/modules/wod13/lombard.dm
Makes it so tuna costs 125 and catfish costs 50.
It will be more realistic as tuna is better than catfish.
:cl:
tweak: made tuna more expensive and catfish cheaper
/:cl:
> minor fish price adjustment

- code/controllers/configuration/entries/general.dm
- tgui/public/tgui.html
> Changes two references to github repo 👍

- code/modules/mob/living/carbon/human/human.dm
Adds a longer, skill-based timer for climbing attempts.
It will make it more reasonable. Also, Lucia wanted this.
:cl:
tweak: tweaked climbing timer to be skill-based
/:cl:
> Skill-based timer for climbing

- code/modules/client/preferences.dm
Changes starting exp from 10 to 50
People can round out their characters off the bat.
:cl:
tweak: tweaked starting exp
/:cl:
> Changing starting exp

- code/modules/client/preferences.dm
This fixes a bug where dexterity doesn't reset.
Game fix.
:cl:
fix: fixed a bug where dexterity didn't reset
/:cl:
> Fixes dexterity not resetting in character setup

- code/modules/admin/admin_verbs.dm
- code/modules/mob/dead/observer/observer.dm
Removes the awful droning sound that makes me have a headache.
Less annoying ambience.
:cl:
sounddel: removed ghost drone
/:cl:
> Removes the unbearable ghost droning sound

- code/game/machinery/doors/shutters.dm
- code/game/machinery/washing_machine.dm
- code/modules/food_and_drinks/kitchen_machinery/microwave.dm
Reverts microwave and washing machine sprite changes, fixes vault door shutters being destructible.
Fixes.
:cl:
del: Reverted washing machine and microwave sprite change for now
fix: fixed vault doors
/:cl:
> A few small fixes and reverts

- code/modules/wod13/food.dm
changes cola and soda in coffee vendor to coffee and strong coffee, oops
typo fix
:cl:
fix: fixed a typo
/:cl:
> fixes typo

- code/modules/vtmb/ghoul_species.dm
Fixes a typo so ghouls are a little sturdier than the average human.
Playing a ghoul is miserable enough.
:cl:
fix: ghouls not being affected by vitae meals enough
/:cl:
> Heartier Ghouls

- code/modules/wod13/ammostack.dm
- code/modules/wod13/guns.dm
Messes with gun balance but keeps most damage values similar while tweaking arpen and adding varying amounts more general wound chance and firing against an unarmoured limb wound chance to firearms for potentially more slowdown per wound inflicted and better niches filled.
Different guns with burst spray tighter/wider cones.
MP5 magazine from 25 to 30.
Both this and the melee changes could really use some proper testing, hard to get a feel of real balance with wider scale fights happening rather than me shooting at NPCs for test dummies.
It felt unfair to focus on just melee weapons.
:cl:
tweak: Slugs will sting slightly more.
tweak: Crossbow toned down.
balance: Other ammo types
balance: Guns changed to hopefully accommodate more variety.
/:cl:
> Calibre Tweaks

- code/modules/mob/living/carbon/werewolf/lupus.dm
- code/modules/mob/living/carbon/werewolf/transformation.dm
- code/modules/mob/living/carbon/werewolf/werewolf.dm
- code/modules/mob/living/carbon/werewolf/werewolf_update_icons.dm
- code/modules/mob/living/simple_animal/friendly/cat.dm
- code/modules/vtmb/disciplines.dm
- code/modules/vtmb/gamemodes/subsystem.dm
- code/modules/vtmb/jobs.dm
- code/modules/vtmb/npc/beastmaster.dm
- code/modules/vtmb/vampire_clane/tzimisce.dm
- code/modules/vtmb/werewolf/gifts.dm
- code/modules/vtmb/werewolf_species.dm
- code/modules/wod13/npcroles.dm
Check old changelogs for majority; mostly flattened numbers back down after looking at their sturdiness, without the broken rage heal equation in factor they feel much better in tests.
Heal does about ~70 heal a pop every 15s. Universally lowered garou ability cooldowns from 20s to 15s.
+Garou now no longer a bit too unkillable while retaining ferocity
+ 100% sharpness gets the boot alongside other claw adjustments, a limb on every street corner is no more
Currently feels good enough for actual testing.
+ Later addition of late party number corrections, they were old values more designed for 50+ pop.
A more fair chance for wolves to not be ground into paste.
:cl:
del: My patience for writing changelogs
tweak: numbers go look and give feedback instead of scream at me
/:cl:
> All-in-one Wolfing

- code/modules/vtmb/jobs.dm
- code/modules/wod13/decor.dm
Fences are no longer climbable and fixes chinese being called draconic in job.dm
Because it fixes stuff.
:cl:
fix: fixed fence climbing
/:cl:
> fence fix and language patch

- code/modules/wod13/guns.dm
- code/modules/wod13/melee.dm
Makes the uzi and tommygun spray more wildly per original intent.
Adds belt slot wearing for Baron's guitar.
*shrug
:cl:
add: An effort filled changelog later (never)
/:cl:
> Extra Melee/Gun tweaks

- code/game/objects/items/storage/backpack.dm
- code/modules/vtmb/gridventory.dm
Keeps satchels at the 6x6 standard while improving backpacks and duffels back to similar standard they were on old weight class system.
Find out in game if you think your favourite item is too large or small to fit in a satchel and yell at me until it's changed.
No more carrying AR's in a satchel
:cl:
tweak: tweaked inv values I dunno look at the changes
/:cl:
> Gridventory bag limiting

- code/modules/mob/living/carbon/werewolf/lupus.dm
- code/modules/mob/living/carbon/werewolf/werewolf.dm
- code/modules/vtmb/disciplines.dm
- code/modules/vtmb/werewolf/gifts.dm
- code/modules/wod13/melee.dm
compiles, I hate my codelife
not doing another changelog of witty shit no one ever reads
:cl:
add: fixes I dunno
/:cl:
> {EVEN FRESHER} Garou Hardiness etc. buffnerftweak

- code/modules/wod13/melee.dm
- code/modules/wod13/npcroles.dm
ya mom. but also it makes human NPCS sound like Humans instead of people who are drunk or robots that just are not real.
:cl:
add: Added additional lines of text for NPCS because they were lacking before
/:cl:
> Npc chatter banter

- code/modules/mob/living/carbon/carbon.dm
Makes it so you can't jump while grabbed or legcuffed.
Fixes what players have been complaining about.
:cl:
fix: fixed jumping while restrained
/:cl:
> Jumping while pulled or legcuffed fix

- code/modules/vtmb/disciplines.dm
Should fix the valeren issues that were complained about.
Because it fixes it.
:cl:
fix: fixed valeren
/:cl:
> Valeren fix

- code/game/turfs/open/floor/plating.dm
Makes the blackness become dirt instead.
It looks nicer.
:cl:
fix: fixed explosions creating the void
/:cl:
> Makes empty tiles (blown up) become dirt

- code/modules/wod13/npc_movement.dm
Stops NPC mobs from shooting player mobs, whenever player mobs shoot, and have a police ID equipped
Police have to walk on eggshells when fighting kindred in the streets, and now will not have to worry about this near as much, giving them a little more weight when it comes to dealing with kindred.
:cl:
tweak: changed mob retaliation consideration coding
/:cl:
> Cops cop pops

- code/modules/client/preferences.dm
- code/modules/mob/dead/observer/observer.dm
As inelegant as this is, this fixes ghosts being able to hear whispers across the map.
This was a bug and is now fixed.
:cl:
fix: fixed auspex ghosts being able to hear all whispers
/:cl:
> Fixes auspexed ghosts hearing whispers

- tgstation.dme
Some of the new files were not defined. For some reason. Fixed.
Fixes.
:cl:
fix: fixed a new file being undefined
/:cl:
> hotfix_books

- code/modules/wod13/clothcode.dm
Some helmets should still continue to let you have hair.
Reverses an oopsie I made with a previous PR.
:cl:
tweak: tweaked a few helmets and hats
/:cl:
> helmet hair hotfix

- code/_globalvars/phonesnumbers.dm
- code/modules/vtmb/electronics/phones/phone.dm
- code/modules/vtmb/electronics/phones/phone_contact.dm
Finnaly now you can block that annoying caller or remove a contact that you may have wrote wrong a number or name.
Also as a Prince or others you don't need to guess peoples name now, they will have their names right attached to the contacts once they open their phone ( and the important contacts also opened theirs)
I was going to make for a unpublish but it makes more sense if you fuck up that.
Silence option and caller historic will come depending on how fast this is merged.
Compilled tested and tested ingame if it works.
Fixed the conflict merges.
More options to the phone, it is not near perfection but got more stuff that it should have since the start.
:cl:
add: Important Contacts got names attached to it now.
add: Remove Contacts option.
add: Block and Unblock options.
/:cl:
> Update to Phones, add Remove, Block , Unblock, Important contacts also now got their names.

- code/modules/vtmb/gamemodes/bloodhunt.dm
- code/modules/wod13/quirks.dm
- code/modules/wod13/special_shit.dm
Small QoL of life feature. But since when do you execute someone just for funsies? All royalty gets to proclaim the reasons for which they execute their enemies.
It gives more context to everyone about why someone is getting blood hunted, as blood hunts are a very serious thing. It will make people less... uncaring about them as well, if they know the reasons.
:cl:
add: Added ability to list reason for bloodhunt
/:cl:
> Add a reason to your bloodhunt

- code/modules/wod13/special_shit.dm
Made a minor error. Corrected it. Works fine now.
Bloodhunt reasons are good again. Describing them in length is nice.
:cl:
fix: fixed bloodhunt sanitization
/:cl:
> Fix sanitization for bloodhunt

- code/modules/vtmb/jobs/national_guard.dm
Fixes the National Guard not receiving proper names and gives them random appearance.
It improves upon the NG.
:cl:
add: gave NG random appearances
fix: fixed NG names
/:cl:
> Fixes individual NG namings, gives them random appearance and gender.

- code/modules/vtmb/vampire_clane/kiasyd.dm
BOGOS BEGONE
Because, it doesn't give verin and I another aneurysm putting up with the jokes
:cl:
Fixed the Kiasyd description
> PHOTOS PRINTED

- code/modules/wod13/guns.dm
This PR makes the flamethrower good and deadly. It was not very good before. Now it is.
It can actually hit people, even if they're trying to run away, whereas before it was nearly impossible to light someone on fire as they'd just move before the flames caught up.
:cl:
tweak: tweaked the flamethrower
/:cl:
> Makes flamethrower good

- code/modules/wod13/wallcode.dm
Kindred were able to walk through acid carelessly. Now they are not.
Kindred still have the advantage over others where environmental hazards are concerned, but they are not immune to it.
:cl:
tweak: tweaked acid floor damage
/:cl:
> Buffs acid pools

- code/_onclick/other_mobs.dm
- code/game/objects/structures/petrified_statue.dm
- code/modules/mob/living/carbon/carbon_defines.dm
- code/modules/mob/living/carbon/werewolf/damage_procs.dm
- code/modules/mob/living/carbon/werewolf/lupus.dm
- code/modules/mob/living/carbon/werewolf/transformation.dm
- code/modules/mob/living/carbon/werewolf/werewolf.dm
- code/modules/mob/living/carbon/werewolf/werewolf_defense.dm
- code/modules/spells/spell_types/godhand.dm
- code/modules/vtmb/werewolf/gifts.dm
- code/modules/vtmb/werewolf/tribes.dm
- code/modules/wod13/ammostack.dm
- code/modules/wod13/melee.dm
**PROBABLY READY FOR A TEST MERGE TO MAKE ALL THE GAROU MAINS CRY**
I really need live testing for a lot of this since it's insanely hard to test a lot of this local.
Cuts down the absurd values that had crinos form being too insane of a mix of hp, armour (which was nullifying damage weaker than the werewolf_armor value seemingly?) and speed. These are a middle ground between the old values garou's crinos form had on the ru server and what they are currently.
Tones down hispo's speed and bite power. 
Adjusts some rage/gnosis costs of gifts or swaps some auspice gift's cost from using gnosis to rage without making them unusable for certain breeds forms/too heavy of a rage cost to use in battle.
+ Attacks the paralyze var so glasswalker zap isn't as stupid (credits to the other wolf PR I …
> [TEST MERGE ME PLEASE] Puts Garou in the bin forever

- code/__DEFINES/role_preferences.dm
- code/__HELPERS/names.dm
- code/game/gamemodes/objective.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/one_click_antag.dm
- code/modules/vtmb/jobs/swat.dm
- tgstation.dme
Adds the SWAT counterpart of the National Guard. Significantly weaker. Admins can set their objective. No spawn point in place but they should spawn at the usual latejoin spots.
Gives the admins a less hardcore tool to send in humans to deal with vampire nonsense.
:cl:
add: Added SWAT admin spawn
/:cl:
> Admin spawned SWAT

- code/modules/wod13/melee.dm
"WATCH OUT HE'S GOT A DOOR!" is no more. Why was this even a thing..?
Fixes a silly issue.
:cl:
fix: fixed doors calling SWAT on you
/:cl:
> Doors no longer summon SWAT on you

- code/modules/vtmb/gamemodes/bloodhunt.dm
- code/modules/wod13/special_shit.dm
Reverts WorldOfDarknessXIII/World-of-Darkness-13#416
> Revert "Makes bloodhunt name the author"

- code/modules/client/preferences.dm
I don't know if this works as I can't replicate the original issue locally. Let's hope for the best...
Fix.
> Bandaid patch for a certain issue that may or may not work

- code/controllers/subsystem/humannpcpool.dm
- code/modules/wod13/npc_movement.dm
NPCs are already limited to respawning only up to 130, and though this supposedly optimizes their routes, it is kind of annoying as they tend to randomly disappear. From my tests of 10+ minutes nothing went wrong, although if you follow one around you'll notice he's walking in circles - but that doesn't matter, it's better than them popping out of existence.
It will make it easier to handle and deal with NPCs, kidnap them, and such.
:cl:
tweak: tweaked NPCs
/:cl:
> Removing random NPC despawn

- code/modules/client/preferences.dm
Just another attempt at fixing a possibly game-breaking bug... And possibly the last.
Fixes a bug.
> Another attempt at fixing this supposed crashing bug

- code/_globalvars/misc.dm
> New year is here. Christmas is over.

- code/modules/mob/living/carbon/human/species_types/humans.dm
- code/modules/vtmb/electronics/atms/atm.dm
- code/modules/vtmb/ghoul_species.dm
- code/modules/vtmb/jobs/jobs.dm
- code/modules/vtmb/kindred_species.dm
- tgui/packages/tgui/interfaces/Atm.js
- tgui/packages/tgui/interfaces/Atm/AtmLogin.js
- tgui/packages/tgui/interfaces/Atm/AtmMain.js
- tgui/packages/tgui/interfaces/Atm/index.js
Makes the ATMs use a TGUI interface - includes being able to log in, log out, change your pin, transfer money to a selected bank account, and a search function. Also of course allows taking money out or depositing it.
Makes the very poor ATM system significantly better and more up to standards.
:cl:
add: Added TGUI  and new features to ATMs
/:cl:
> [Draft] TGUI ATMs

- code/modules/vtmb/jobs/anarchs/baron.dm
- code/modules/vtmb/jobs/anarchs/bouncer.dm
- code/modules/vtmb/jobs/anarchs/emissary.dm
- code/modules/vtmb/jobs/anarchs/sweeper.dm
- code/modules/wod13/food.dm
For some reason, Ministry weren't allowed to join as Anarchs. This made no sense, considering fucking gargoyles and kisayds can - as well as many other exotic clans/bloodlines - when many members of the Followers of Set already agree with the moral views of most Anarchs. Also Tremere can now Be Anarchs but Not the Baron. I Encourage the Chantry to Hunt Them Down and Kill Them and Shit. 
It compiles. Works fine. It's literally just five lines of code.
Tremere Antitribu Still Exist FUck You Fuck You Fuck You Fuck you Fuck y-
:cl:
add: Gave Ministry the ability to play as Anarchs. 
add: Gave Tremere the ability to play as Anarchs
/:cl:
> Tremere Anarchs & Ministry Anarchs 

- code/modules/vtmb/kindred_species.dm
Ghouls can't get keep their disciplines after being embraced anymore.
Fix;
:cl:
fix: FIx exploit 
/:cl:
> [HOTFIX] Embrace Ghoul Exploit

- code/modules/wod13/witness.dm
Removes exact co-ordinates from dispatch
Exact co-ords are a little silly, this is going to make whoever's using dispatch have to put in effort.
:cl:
balance: rebalanced dispatch
/:cl:
> Dispatch nerf

- code/modules/vtmb/electronics/p25.dm
- code/modules/wod13/narco.dm
Makes it so that weed's growth stages properly update, mobile methlab now has a chance to explode and loses condition the more meth you cook. Weed also now has a chance to drop more than 1 piece of weed based on your mentality. And fixed that stupid compiling error from another PR.
Makes the mobile methlab less abusable, makes weed more worthwhile, fixes broken stuff.
:cl:
fix: fixed a few drug production related issues
fix: fixed compiling error from another PR
refactor: changed variable weeded to growth_stage
balance: changed drug production up slightly
/:cl:
> drug adjustments and fixes

- code/modules/projectiles/ammunition/_firing.dm
- code/modules/vtmb/frenzy.dm
- code/modules/vtmb/ghoul_species.dm
- code/modules/vtmb/jobs/police.dm
- code/modules/vtmb/jobs/prince.dm
- code/modules/vtmb/jobs/sheriff.dm
- code/modules/wod13/npc.dm
- code/modules/wod13/onyxcombat.dm
- code/modules/wod13/witness.dm
Police chief now starts with CQC, badges no longer protect you from the law, you now need at least 2 witnesses, and they must be alive for it to be reported on a dispatch radio, minor refactoring of some code, police, prince and sheriff are immune to SWATting
It fixes some things and makes others more reasonable
:cl:
add: Gave the Police Chief CQC
tweak: tweaked things that prevent your arrest by NPCs
fix: fixed dead NPCs being able to report you
refactor: refactored some police report code
/:cl:
> CQC Police Chief, Witness fixes, badge changes

- code/modules/vtmb/gridventory.dm
refresh_mob_views() is being called way too many times by too many procs. I'm too lazy to fix it, but we can get rid of the lag caused by backpacks by making sure we're not redrawing the same underlay repeatedly
:cl:
/:cl:
> backpack no longer lags your game

- code/modules/vtmb/gridventory.dm
- code/modules/wod13/car.dm
- Pulling someone out of a car (Alt+click) takes half as long, and you can no longer enter a car instantly
- Repairing is now a continuous action that heals 4 hp for every second spent repairing it (same rate as before)
- Camera will be pushed further forward the faster the car is driving, giving the driver more time to react to any obstacle that appears, hopefully now you will see more people using cars to get around FAST
I've asked several people why they don't use cars to get their faction members around the map, and the consensus seems to be "It's too much trouble to be worth it". After this, I'll push another PR improving car handling, adding semaphores, making cars more easily obtainable to all players, and reprogramming NPCs to respect traffic law. Hopefully after this we'll have …
> Car rebalancing & QOL pt. 1

- code/modules/wod13/car.dm
i used the wrong operator. the shame is unbearable
i'm sorry
:cl:
fix: You can now have multiple people inside cars
:cl:
> cars are no longer one seaters

- code/modules/wod13/doorcode.dm
Gives Toreadors access to their clan's Torea-Doors.
Makes it so the clan can actually access the places they are meant to?
> Fix Toreador access to Torea-Doors

- code/datums/keybinding/human.dm
- code/modules/wod13/onyxcombat.dm
I WAS MADE FOR LOVING YOU BABY
With "Bloody lover" quirk, you're "kissing" instead of biting. It should help for bystanders to understand that in fact, you just love a random hobbo and you're not drinking his blood.
changed text and font appearing while biting with bloody lover quirk... I mean I wrote it like three times already
> Bites with bloody lover now looks like a kiss

- code/__DEFINES/_helpers.dm
- code/modules/vtmb/disciplines.dm
- code/modules/vtmb/gridventory.dm
Pending testing in ~2 hours from me PRing this: Obfuscate will end and go into a cooldown of 60 seconds (down to a minimum of 30 seconds if you have level 5+) if you perform an action with an object on anything.
I was not aware that we had no code whatsoever to break Obfuscate if you just went bananas with a gun and this needs to be addressed immediately. I would merge now but I'm pushing this from work and still need to test it.
:cl: Bisar
fix: Obfuscate is no longer an impenetrable invisibility cloak.
/:cl:
> Obfuscate hotfix; no more invisible murder [EMERGENCY HOTFIX, LIABLE FOR REVERT PENDING RETROACTIVE REVIEW]

- code/__DEFINES/colors.dm
- code/modules/mob/mob_say.dm
- interface/skin.dmf
This reverts commit 922209f987e78fa21561806a9d0efb46a2f18758.
> Revert "Fixes input-bar say being broken, WIP tweaks for interface (#543)"

- _maps/map_files/Vampire/SanFrancisco.dmm
Just few small fixes, cuz after merging shenanigans few objects were deleted from the map
*FIXED*
*OLD*
*FIXED*
*OLD*
*FIXED*
*OLD*
*FIXED*
*OLD*
fixes misplaced bottles in the morgue
fixes clinic director spawn
fixes organ freezers that were absent
fixes misplaced p25 transmitter
few other small fixes mostly with layers
> Fixes: The Clinic

- code/modules/vtmb/frenzy.dm
People who Wighted or became Chih-mei spammed the frenzy subsystem (this thing needs to be annihilated) with hundreds of copies of themselves, basically killing the server due to extreme lag. This PR fixes that issue.
No more mysterious server annihilation.
:cl:
fix: Wighting no longer breaks the server.
/:cl:
> Fix frenzy bug

- code/modules/wod13/npc_aggression.dm
Fixes an oversight in the faction removal PR that allowed NPCs to aggro on each other.
Cops killing each other is funny, but not very good.
:cl:
fix: NPCs no longer kill each other.
/:cl:
> Fix NPCs killing each other

- code/modules/wod13/car.dm
Caused by a commit I pushed onto it, would have let handcuffed people steer. Nothing horrendous but needs fixing.
kill bug
:cl:
/:cl:
> Fixes small oversight in car rework PR

- code/modules/vtmb/jobs/fbi.dm
FBI doesn't get suspicion and so on. Finally FBI players will be on the same level as policemen.
FBI now has warrant flag
> FIX: FBI WARRANT

- code/modules/admin/sql_ban_system.dm
Tentatively implements the missing html button for job banning in the ban panel
:cl: Bisar
/:cl:
> implements job bans?

- code/modules/wod13/npc.dm
- code/modules/wod13/npcroles.dm
De-slav janks some the NPC dialogue. Just a little. Mainly for police & strippers.
Rewrites/fixes some NPC dialogue that either made no sense or had various syntax errors. Also made the stripper dialogue Slightly Less Explicit
Better dialogue makes the game seem...immersive? And not like a cobbled together shitheap.
Compiles on my machine.
:cl:
No more Slavjank Dialogue. Yippie.
/:cl:
> You Got Some Bullets For Those Crime Ass Ideas?

- code/modules/vtmb/electronics/atms/atm.dm
See above. No credit is involved.
:cl:
spellcheck: It's a debit card, not a credit card.
/:cl:
> Debit not Credit

- code/modules/mining/machine_vending.dm
So we added the empty one, not the filled one. this PR fixes that
Self healing and survability on the field.
:cl:
Allows PD to buy the right IFAK
/:cl:
> Adds the right Ifak to the PD

- code/__DEFINES/colors.dm
- code/modules/client/client_procs.dm
- code/modules/mob/living/carbon/carbon_say.dm
- code/modules/mob/mob_say.dm
As the title says; you can type in the bottom input bar if you prefer to be able to press tab to enter communication instead of using the hotkey.
:cl: Bisar
fix: fixes coloring and an input command
/:cl:
> Fixes say without breaking hotkey say, fixes coloring on input bar

- code/game/objects/items/cigs_lighters.dm
- code/modules/hydroponics/grown/cannabis.dm
- code/modules/reagents/chemistry/reagents/drug_reagents.dm
- code/modules/wod13/narco.dm
Ported cannabis from TGstation.
> Properly replaces space drugs with weed in green packages and leaves

- code/modules/vtmb/jobs/citizen.dm
allows gargoyles to join round in the citizen role
gray people deserve nights off too, let them b free
> let gargoyles be citizen

- code/modules/wod13/ambient.dm
Adds Fire Suppression to the Church.
The Church is regularly set on fire, causing the priest to lose their entire building and base almost every other round. This won't stop the building from burning entirely, and committed people will still be able to wreck it if they want to, but this should help priests and their church last a little longer.
:cl:
add: Added Fire Suppression to Church
:cl:
> Adds Fire Suppression to Church

- code/modules/vtmb/dharma.dm
Reverts WorldOfDarknessXIII/World-of-Darkness-13#654
> Revert "Dharmic Adjustments/Additions"

- code/modules/vtmb/dharma.dm
This disables Kuei-jin being able to commit sins or virtuous acts in their Dharma to decrease or increase it.
The entire sins/virtues system was terribly implemented, and only being able to increase it in-round wouldn't be very balanced. 
:cl:
tweak: Kuei-jin can no longer increase or decrease Dharma in-round.
/:cl:
> Disable in-round Dharma rise/fall

- code/modules/vtmb/electronics/phones/phone.dm
Makes payphones actually show in game
It's good to see things in order to use them
:cl:
fix: payphones now show
/:cl:
> make payphones actually show

- code/modules/wod13/decor.dm
Fixes one (1) letter in a sign.
Makes the game playable again
<details>
</details>
:cl:
fix: Fixes a typo in the Police Department sign.
/:cl:
> Fixes a typo in the police department sign

- code/modules/vtmb/power/discipline/obfuscate.dm
Deactivation doesn't automatically make an ability inactive, so we need to deactivate obfuscate so it doesn't try to refresh when nonfunctional.
<details>
</details>
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
map: added/modified/removed map content
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: …
> Another obfuscate hotfix

- code/modules/vtmb/power/discipline/temporis.dm
I accidentally forgot to set Temporis as whitelisted, mea culpa
<details>
</details>
:cl:
fix: You can no longer freely access Temporis.
/:cl:
> Fixes Temporis whitelist

- code/modules/cargo/expressconsole.dm
Fixes the issue that's been in for over a month. https://github.com/WorldOfDarknessXIII/World-of-Darkness-13/issues/737
Fixes a potentially game breaking issue.
<details>
</details>
:cl:
fix: fixed cargo console bug
/:cl:
> Infinite Order bug fix

- code/modules/vtmb/power/discipline/auspex.dm
Makes Auspex properly deactivate, making you not blue forever.
<details>
</details>
:cl:
fix: Auspex now properly deactivates.
/:cl:
> Auspex 3 hotfix

- code/modules/mob/living/blood.dm
- code/modules/mob/living/carbon/carbon_defines.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/simple_animal/hostile/regalrat.dm
Fixes simplemobs having infinite blood due to them having zero blood in their bodies (DIVISION BY ZERO FUCK YEAHHHHH). Also makes bloodloss less punishing by doubling the rate you regain it.
Fixes a bug and makes things less CBT.
<details>
</details>
:cl:
fix: Simplemobs no longer have infinite blood.
tweak: Mortals now regenerate blood at double the speed.
/:cl:
> Fix blood feeding

- _maps/map_files/Vampire/SanFrancisco.dmm
Maps the following changes:
- Replaces the Prince's Sauna with a washroom and shower.
- Removes two extra wallpaper interfering with wall smoothing in the Prince's bedroom.
- Adds a single light to the MT2 Showers.
Players requested a shower and the sauna is never used. Wall smoothing important. Showering in the dark dangerous for health.
<details>
</details>
:cl:
map: Replaces the Prince's Sauna with a washroom.
map: Fixes some minor oversights with lights and wallpaper in the Tower.
:cl:
> Minor Tower Touch-Ups

- code/controllers/configuration/entries/game_options.dm
- code/controllers/configuration/entries/resources.dm
- code/controllers/subsystem/ticker.dm
- code/game/world.dm
- config/config.txt
Does as the title says. Doesn't replace our save files with json yet, but it's the first step toward the conversion so we have all the savefiles at hand in the right format.
Thankless backend scutwork is the foundation of any society
<details>
</details>
:cl: Bisar
code: Savefiles get converted into json at the end of the round.
/:cl:
> Converts all save files to json at round end

- code/modules/wod13/guns.dm
Molotovs can no longer stay lit indefinitely, instead they explode between 15 to 45 seconds after being lit. 
People have a habit of lighting molotovs and stuffing them in their bags to use later. It's incredibly LRP.
https://github.com/user-attachments/assets/6f917a16-9271-41ef-8190-445d56bd1180
<details>
</details>
:cl:
Molotovs now explode between 15 and 45 seconds after being lit.
/:cl:
> Make molotovs explode a random amount of time after being lit

- code/modules/wod13/food.dm
tiny update to a single item description
people know what cholesterol is
<details>
it compiled i prommie
</details>
:cl:
fix: changed word in description
/:cl:
> Pedantically change cholesterine to cholesterol

- code/modules/cargo/expressconsole.dm
#818 got lost in the reset, this redoes it.
Edit: Moved the check to before every action, so you cannot reset/spam order anything, either.
It restores an already done fix, makes it more foolproof.
<details>
https://github.com/user-attachments/assets/47ec97d2-3a31-4334-a36f-54861b39da9d
</details>
lucifernix:
- Fixes the infinite order bug in the Warehouse.
> Infinite Order bug fix 2

- code/modules/unit_tests/plantgrowth_tests.dm
I didn't notice that plantgrowth_tests.dm uses assets from `goon/` in my degoonification (#789) PR, my bad. This should make CI compile properly.
CI compiles!!!
<details>
Before:
After:
</details>
:cl:
server: Fixed plantgrowth_tests.dm
/:cl:
> Fixes plantgrowth_tests.dm

- _maps/map_files/Vampire/SanFrancisco.dmm
Adds a mixer and a rag to da club
better bar rp
:cl:
add: a mixer and a rag to da club
/:cl:
> Adds mixer and rag to da club

- code/modules/vtmb/jobs/anarchs/bouncer.dm
- code/modules/vtmb/jobs/anarchs/emissary.dm
- code/modules/vtmb/jobs/anarchs/sweeper.dm
Add's the Ability for salubri to play all anarch roles besides the baron 
Salubri have been sheltered among the anarchs historically and there are very few roles for salubri to play besides citizen , doctor , gravedigger.
<details>
https://github.com/user-attachments/assets/59e9cf2d-e1ec-47c2-80bc-40268313f88e
</details>
:cl:  URBANMECH
Lets Salubri Play Emissary/Bruiser/Sweeper  
/:cl:
> Salubri 4 anarkz

- code/modules/vtmb/dharma.dm
<details>
</details>
:cl: XeonMations
code: code compiles now on 514
/:cl:
> fucking stupid fucking 514

- code/modules/vtmb/vampire_clane/banu_haqim.dm
- code/modules/vtmb/vampire_clane/lasombra.dm
- code/modules/vtmb/vampire_clane/tzimisce.dm
A few polls were run in staff chat about if some Clans should remain whitelisted. The vote concluded, and staff voted to allow all players to have access to the main 13 Clans. Other splats (mostly due to jank, or being far too powerful, or most people knowing nothing about their lore) will remain whitelisted, along with niche bloodlines. This unwhitelists Banu Haqim, Lasombra, and Tzimisce.
We don't have much reason to restrict these Clans anymore.
<details>
</details>
:cl:
Banu Haqim, Lasombra, and Tzimisce are no longer whitelisted.
/:cl:
> Unwhitelist The Main 13 Clans

- _maps/map_files/Vampire/SanFrancisco.dmm
This is #953 , except adapted to fit into the updated dwelling map.
> Jazz club changes, redux

- _maps/map_files/Vampire/SanFrancisco.dmm
Reverts WorldOfDarknessXIII/World-of-Darkness-13#960
> Revert "Jazz club changes, redux"

- code/modules/vtmb/jobs/prince.dm
The announcement about the Prince role being filed is now properly sent again, done after https://github.com/Near-Web/The-Final-Nights/pull/279
> Fixes Prince announcement 

- code/modules/wod13/delivery/delivery_datums.dm
- Makes the winner of the crates delivered portion of the delivery summary at round end be properly highlighted
> Post round display fix

- code/modules/admin/sql_ban_system.dm
- html/admin/banpanel.css
This ports https://github.com/Near-Web/The-Final-Nights/pull/332
Checked locally and everything seems to go but actual dbase compatibility needs to be tested server side. TFN's side seems to confirm it works though, so we should be gtg.
> Ports jbans from TFN

- code/game/objects/structures/window_frames/window_frame.dm
- Adds smoothing variables to the window frame so its icon properly blends with adjacent walls.
> Adds icon smoothing to the window frames

- code/modules/wod13/items/keys/keys.dm
Nuff said. This also means that everyone from a faction will be able to open/close the truck but NOT be part of the delivery. This is so faction members can easily open/lock the garages without needing to be part of the delivery.
> Adds factional delivery office access to factional keys

- code/datums/components/crafting/recipes.dm
- code/game/objects/items/miscellaneous.dm
- code/modules/hydroponics/grown.dm
- code/modules/hydroponics/grown/flowers.dm
Why was the sunflower pathed outside of the /food/ tree? I don't know!
This fixes it. Makes them bigger or smaller depending on final potence and also sell right.
Also reduces the sell price of bouquets and flowers by 30%. As expected.
Tested locally, grown a full sunflower and sold it.
> Fixes sunflower pathing, adjusts produce sell prices.

- code/modules/client/preferences.dm
- code/modules/vtmb/dharma.dm
- code/modules/vtmb/kuei_jin.dm
Removed Dharma and Gen HP from KJs and Vampries Respectively (also fixes KJs stats not showing bonus stuff)
Which means Gen 7 Vampires will no longer be super duper oppressive!!! (stronger blood heal but eh least they need to spend HP to be tanky)
Yeah true Splat REwork means this needs to be refactored, but it'll take a long time and honestly a band-aid will be pretty helpful ngl
Also made it so KJ stats also included bonuses shown so that's one good thing wohoo
Last I check lots of people complained about elders being super  durable so put a pin on that so it's all  good now!
<details>
</details>
:cl:
add: Added new mechanics or gameplay changes
add: …
> Removed Dharma and Gen HP from KJs and Vampries Respectively (also fixes KJs stats not showing bonus stuff)

- code/modules/vtmb/werewolf_species.dm
- Garou can now see their bank account PINs in their About Me display.
> Fixes banking info for Garou

- code/modules/mob/living/carbon/human/species_types/humans.dm
- code/modules/vtmb/ghoul_species.dm
- code/modules/vtmb/kindred_species.dm
- code/modules/vtmb/kuei_jin.dm
- code/modules/vtmb/werewolf_species.dm
- Adds paragraphs and changes the flow of the About Me window for all species. Codes are now displayed near the top.
This will be annihilated by the species rework most likely, but I really don't care.
> Adds paragraphs and changes the flow of the About Me window

- code/modules/mob/living/carbon/human/species_types/humans.dm
- code/modules/vtmb/ghoul_species.dm
- code/modules/vtmb/kuei_jin.dm
- code/modules/vtmb/werewolf_species.dm
- This propagates the padding added to the kindred About Me window to the other species. I forgor :U
> Adds padding to non-kindred About Me views
