- code/modules/ziggers/umbra.dm
Fixes a bug where Penumbral monsters were passing through portals and randomly appearing in places like the theatre.
No more chantry getting ripped apart by the white wolf! No more big-dicked monster popping into the material realm!
:cl:
fix: NPCs can no longer pass through umbral gateways. The white wolf and weird monster will stay in the Penumbra.
/:cl:
> Only players can pass through umbral gateways.

- tgui/packages/tgui-panel/chat/constants.js
Holy fucking shit, why do we have this? Removes the "Lewd Messages" tab from fancychat's tab feature. 
We are not an ERP server. We have none of these.
:cl:
del: Lewd Messages tab in fancychat.
/:cl:
> Remove Lewd Messages tab from tgui

- code/modules/vtmb/vampire_clane/lasombra.dm
Changes the time of several Obtenebration actions to appropriately represent levels and blood costs.
Previously, both 3rd and 4th level Obtenebration actions lasted TEN SECONDS. That is terrible.
:cl:
changed Summon Tentacles duration from 10 seconds to 30 seconds
changed Shadow Armor duration from 10 seconds to 40 seconds
/:cl:
> Obtenebration balances

- code/controllers/subsystem/humannpcpool.dm
- code/modules/mob/mob_movement.dm
- code/modules/vtmb/gamemodes/masquerade.dm
Minor fixes so that observer movement doesn't constantly try to divide by 0, and NPCs don't print out a message whenever they spawn. Also makes the Masquerade value display as "stable" when it's above 1000 to prevent weird bugs with it going over. Will try to make sure it never goes over in the future, but this was just necessary to improve the code.
It's easier to see what's going wrong when there isn't 1000 runtimes every time a ghost moves! Also allows for Masquerade to still mostly work when overflowing.
:cl:
fix: Masquerade values above 1000 now display as stable.
refactor: No more log spam from observer moment and NPC spawning!
/:cl:
> Cleaned up server log + added default case for Masquerade

- code/modules/vtmb/disciplines.dm
- code/modules/vtmb/ghoul_species.dm
Makes all of the discipline sounds local to the player. Changes fortitude to have no extremely obvious visible icon effect.
Maintaining the masquerade is easier when your non-obvious disciplines remain non-obvious. Likewise, the lack of sound indicators is both more lore accurate and does also help people to stay on their toes about who's a kindred using powers.
:cl:
tweak: tweaked fortitude and other disciplines
/:cl:
> Discipline tweaks

- code/modules/vtmb/disciplines.dm
Adds documentation to variables used in /datum/discipline, and removes the check while casting to see whether the caster is currently knocked down. This lets people use Disciplines even when on the floor from something like Potence.
The meta is currently just knocking someone down and beating them up while they're incapable of resisting in any way. It's time to let go of that nonsense.
:cl:
tweak: You can now use Disciplines while knocked down. No more helplessly lying on the floor after getting Potence punched!
/:cl:
> Enable disciplines while lying down

- code/modules/vtmb/vampire_clane/baali.dm
In this pull request I do a magic trick that makes it so Baali are actually Baali! I achieve this mistifying effect by swapping their second discipline from Obtenebration to Presence!
Obtenebration is super wack in-game, also lore accuracy. Also also, back in the Age of Flav Baali donators chose Obtenebration because it was shrimply better than Presence.
:cl:
tweak: Changed Baali's second discipline to Presence.
/:cl:
> De-Azanealification of Baali

- code/modules/vtmb/electronics/keypads/keypad.dm
Fixes 0's not being registered by the keypad if they are at the front.
Bugfix
:cl:
fix: fixed a keypad bug
/:cl:
> Keypad fix by @lucia

- code/modules/client/preferences.dm
Changes character creation so that all new characters start with default stats instead of copying their stats from the first character slot.
Fixes the bug that was letting people clone their characters and basically start a new one with a jumpstart on progression, or avoid progression loss by saving their state before losing it.
:cl:
fix: New characters no longer have their stats copied from the first character.
/:cl:
> Fix new characters copying stats from slot 1

- code/modules/wod13/quirks.dm
Disables the quirk Black Secret indefinitely
It prevents people in the short and long-term from abusing it unless they have an actual good story reason for being cloaked with it being able to have it returned to em by admins.
:cl:
Black Secret has been commented out until rework occurs.
> Disables Black Secret

- code/modules/vtmb/frenzy.dm
- code/modules/vtmb/ghoul_species.dm
Makes it so camarilla roles are not attacked by SWAT raids for wielding weapons.
I believe this will make playing camarilla roles a far more attractive proposition, will allow Camarilla to operate more strongly than other factions within a martial capacity. If they can walk over the streets during a Sabbat attack or a hunt for a serious masquerade breacher with their weapons - good. If they are in a factional war, this is their advantage. As is, nobody wants to play Camarilla and my intention is that playing Camarilla is both more fun and attractive.
:cl:
tweak: tweaked camarilla so they won't get swatted for gear
/:cl:
> Camarilla will not get SWATted

- code/game/objects/items/cigs_lighters.dm
Alters smoking lung damage to give you about a tenth of what it normally does. That's it.
Not tested, but it's just a number change. 
Trying to roleplay as a nicotine addicted kine? Time to not die after smoking three cigarettes!
Genuinely though, I do feel like smoking lung damage needs to be retuned at least slightly, actual numbers should be good to play with. 
:cl:
balance: Smoking no longer deals excessive lung damage
:cl:
> Less Smoking Lung Damage

- code/modules/client/preferences.dm
It used to be that lockpicking at level 0 showed you that it costs 0 exp. Should show properly now.
It fixes a bug.
:cl:
fix: fixed a lockpick purchasing bug
/:cl:
> Fixing minor lockpicking purchase bug

- code/modules/admin/admin_verbs.dm
Makes some edits to admin commands to remove redundant ones (enciper, deciper), improve bad ones (aghost), fix broken ones (toggle canon), and actually log ones that can be abused (reward experience).
Makes it easier to do admin stuff.
:cl:
admin: Fixed toggle canon, made rewarding experience actually get logged, and improved aghosting.
/:cl:
> Improve admin verbs

- code/modules/vtmb/disciplines.dm
Changes Dominate to be more tabletop-accurate, meaning that you cast it using your social attributes and you cannot cast it on people of a lower Generation. Generation no longer factors in besides that.
More tabletop accuracy is great, and this also makes it easier for humans to resist Dominate.
:cl:
balance: Dominate no longer works on lower Generations. Casting dominate now uses social.
/:cl:
> Rebalance Dominate

- code/modules/client/preferences.dm
- code/modules/vtmb/disciplines.dm
- code/modules/vtmb/jobs.dm
Makes the Old Clan Tzimisce unable to learn vicissitude, Bogatyr and Voivode become Old Clan only.
More accurate to the Old Clan Tzimisce in the lore. Makes them more unique.
:cl:
tweak: tweaked Old Clan Tzimisce
/:cl:
> Removing Vicissitude from Old Clan, Old Clan manor is Old Clan only.

- code/_onclick/item_attack.dm
- code/game/objects/items.dm
- code/game/objects/items/flamethrower.dm
- code/game/objects/structures/tables_racks.dm
- code/modules/food_and_drinks/drinks/drinks/bottle.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defense.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/projectile/magic.dm
- code/modules/vtmb/disciplines.dm
- code/modules/vtmb/gamemodes/bloodhunt.dm
- code/modules/wod13/guns.dm
- code/modules/wod13/melee.dm
Removes getting blood hunted automatically for doing mean things in the Elysium.
Sometimes even Princes get bloodhunted for something like throwing a rock. The mechanic makes you question if a Bloodhunt was placed with intent or if someone accidentally shot a gun in the elysium. It adds nothing to the game, and without it it will be better.
:cl:
del: Removed elysium auto-bloodhunt
/:cl:
> Removing Elysium Bloodhunts

- code/modules/spells/spell_types/construct_spells.dm
- code/modules/spells/spell_types/forcewall.dm
- code/modules/vtmb/disciplines.dm
- code/modules/vtmb/vampire_clane/salubri.dm
Salubri 2nd discipline is no longer going to instantly handcuff you, and the 4th will no longer instantly drain your entire bloodpool. 5th also does not revive the dead any longer.
Instead, the 2nd discipline allows you to make a kindred drowsy and a mortal to fall asleep for 30 seconds. 4th discipline allows slightly better healing than 3rd, and gives you the ability to create walls around yourself for protection for a short time.
5th discipline allows you to increase the humanity of other kindred.
It nerfs an extremely overpowered auto-win discipline and makes it more lore accurate.
:cl:
add: redid half of the valeren discipline
del: deleted some old valeren powers
/:cl:
> Salubri discipline changes

- code/modules/vtmb/artifacts.dm
This fixes the problematic aspect of key of alamut that was some were abusing by stacking two, in order to make themselves almost invulnerable to bullets.
Defense buffs are good, being immune to damage is bad.
:cl:
balance: rebalanced Key of Alamut. Now, if you have two of them equipped, only one will work, and you need to unequip both, then re-equip one, to get the bonuses again.
/:cl:
> Fixes doubling Key of Alamut

- code/modules/client/preferences.dm
Changes Generation lowering XP cost to the 20 listed instead of 10
removes confusion, and new players can no longer dump every starting XP point on generation, making them upgrade some stats or disciplines.
:cl:
tweak: tweaked xp costs for generation lowering
/:cl:
> Fixes Generation XP Costs

- code/modules/mob/living/carbon/werewolf/life.dm
Gives garou the ability to fix their veil score progressively by spending time in the penumbra universally or their tribe's varying areas. Currently IT ALL JUST WORKS.
No more wolves breaking global masq by being seen in crinos with no way to fix it.
:cl:
tweak: tweaked myself closer to an aneurysm
/:cl:
> Your Big Fat Garou veil recovery hotfix

- code/controllers/master.dm
Scourge is a generally unrewarding job, and I thought it was really weird that the role doesn't get it given how important it is to the health of the masquerade and, by extension, the round.
This PR just rewards Scourges for playing their role and actually want to maintain it, instead of just jumping to Sheriff.
:cl:
fix: Scourges now gain additional XP
/:cl:
> Places scourge under the master file

- code/__DEFINES/wod13.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/vtmb/disciplines.dm
- code/modules/vtmb/frenzy.dm
- code/modules/vtmb/kindred_species.dm
- code/modules/vtmb/pyramid.dm
- code/modules/vtmb/vampire_clane/doc.dm
- code/modules/vtmb/vampire_clane/lasombra.dm
- code/modules/vtmb/werewolf/auspice.dm
- code/modules/wod13/bloodsucking.dm
- code/modules/wod13/procs.dm
- tgstation.dme
This PR is an amalgam of different changes that I was working on today.
- Adds in a dice rolling system for both number of successes and outcome of the roll. 
- Makes Melpominee 2 come up as a forced say in admin logs.
- Makes everyone witnessing Melpominee 2 roll with Mentality to realise that the victim's lips don't match what they're saying. Base difficulty 5, +2 difficulty if the victim is wearing a mask, +1 difficulty if the witness is more than 3 tiles away, and +2 difficulty if the victim is currently typing.
- Adds rudimentary admin logging for all Disciplines.
- Adds text explaining what happened when you Wight.
- Trying to embrace a Garou now rolls their Auspice level, only allowing the Embrace on a botch. They scrunch or stay perfectly still on failure and success.
- Allows …
> Bunch of Fixes and QOL

- code/modules/wod13/food.dm
The following PR allows hospital staff to get a vendor that allows them to restock on goods for the time being as we figure out a gameplay loop. This PR also lets people start to set up their makeshift clinics too to facilitate gimmicks. The vendor needs to be added next map update cycle.
As mentioned above, this allows people to set up their gimmick area if they wanted to be a quirky doctor. Hospital players also asked for this to be added in too.
:cl:
Adds a vendor for the hospital!
Gives the blackmarket dealer a surgical bag.
/:cl:
> Creates a Hospital Vendor & Adds Surgical Kits

- code/modules/vtmb/vampire_clane/ministry.dm
This fixes the previous inability to make the urn a second time. The qdel at the end of the urn action trigger deleted the variable's reference as well, adding a redefinition of urn afterwards fixes this.
Urn on, Urn off
:cl:
fix: fixed bug involving urn creation
/:cl:
> Fixes not being able to make urn a second time

- code/modules/vtmb/jobs.dm
Allows members of the following clans to be Barons:
- Daughters of Cacophony
- Banu Haqim
- Tremere
- Tzimisce
- Caitiff
The latter three are established in White Wolf lore as having some representation in the Anarchs. DoC and BH are permitted as Bouncers, and I'm not sure of a reason why they shouldn't be able to run the bar.
Additionally, Bouncers are now permitted to be any clan that a Baron could be; this opens it up to Tremere and Ventrue.
Yes, Anarch Ventrues or Tremeres are somewhat rare, but they are canon. The rest, I think, are pretty uncontroversial.
:cl:
tweak: Adds DoC, Banu Haqin, Tremere, Tzimisce, and Caitiff to supported clans for Baron
tweak: Bouncers can be in any clan that Barons can
/:cl:
> Expands/makes consistent clan restrictions for Anarchs

- code/controllers/subsystem/job.dm
- code/modules/client/preferences.dm
- code/modules/mob/dead/new_player/new_player.dm
- code/modules/vtmb/jobs.dm
Allows admins to bypass requirements for joining as certain jobs, so they could spawn as a Salubri Regent or a Tzimisce Prince if they so wanted. This also restricts the Prince role from regular Tzimisce and Caitiffs.
Lets admins do more fun stuff hopefully, and dear god the Tzimisce shouldn't be given any power outside of the Sabbat. Caitiffs should also remain politically disenfranchised.
:cl:
admin: You can now join as any job whatsoever.
tweak: Tzimisce and Caitiffs can no longer be Barons.
/:cl:
> Admin Job Requirements Bypass

- code/modules/client/preferences.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/species.dm
additional_physique is a hidden stat that you would gain from the Average trait but it did exactly nothing on the game code, now it is fixed
Stat doing what it was intended
:cl:
fix: the lack of additional_physique stat on the checks that used physique
/:cl:
> Fixed additional_physique doing nothing

- code/modules/vtmb/electronics/atms/atm.dm
Adds green lighting to the ATMs.
What it does it makes every ATM emits green light that isn't very strong.
ATMs tend to hide in the darkness, so it's hard for players to see them or even find them in the first place. This will be helpful for people to find an ATM besides ATMS do emit light anyways.
:cl:
tweak: added green light to the atm
/:cl:
> Adds lighting to the ATM

- code/modules/mob/living/living.dm
Modified the existing TG Grab system to include the WoD Physique Stat
Example : The one who is grabbing has a Physique Stat of 5, the one Resisting has a Physique Stat of 1
The game has a 60% Base chance to resist, since the different is so high it will be now 60 - (50 - 10), ending up with a 20% chance of escaping the grab, the same way if it is reversed their chances will increase to 100%.
Compiled tested, and tested ingame with logs.
More realistic, now if your physique stat is higher than someone, their chances of resisting are lower, if their physique stat is higher their chances of resisting are higher.
:cl:
add: Physique now contributes to grab mechanics.
/:cl:
> Add Physique Scale to Grab 

- code/modules/wod13/npc.dm
- code/modules/wod13/npc_movement.dm
Gotta go... not so fast. This is a minor edit that should make the NPCs move significantly slower. You can even catch up to them without being Usain Bolt! Truly, they seem like they didn't just miss their train and are out on some late night business.
NPCs shouldn't be faster than players, or super fast as they were in general. What was up with that anyway?
:cl:
tweak: tweaked NPC walkspeed
/:cl:
> NPC Slowdown

- code/modules/vtmb/kindred_species.dm
Based on the Tunnel Walrus suggestion, now if you got a primogen it will show on your about me, there are only 5 primogen roles at the moment.
Basically as the suggestion states, you should know your primogen and the about me is a good place to have that information.
:cl:
add: If there is a primogen for your clan, they will show up on your about me.
/:cl:
> Primogen showing on your about me, suggestion: Tunnel Walrus

- code/controllers/master.dm
[Compiled tested and tested ingame]
I was going to make a new var for it but since the only way to get the experience_plus is from the artefact i left the check using the same var, now if you have it on your inventory you will get the experience_plus and at the end of the round if you still have it the xp will be added to your char.
Fix!
:cl:
Fix: Saulocept does something now
/:cl:
> Fix Saulocept artefact giving no xp bonus 

- code/modules/vtmb/electronics/phones/phone.dm
- code/modules/vtmb/electronics/phones/phone_contact.dm
- code/modules/vtmb/jobs/archivist.dm
- code/modules/vtmb/jobs/dealer.dm
- code/modules/vtmb/jobs/prince.dm
- code/modules/vtmb/jobs/regent.dm
- code/modules/vtmb/jobs/seneschal.dm
- code/modules/vtmb/jobs/sheriff.dm
- code/modules/vtmb/jobs/supply_assistant.dm
Fixed two bugs, added some needed contacts to their respective phones, also supply tech and archivist got a new phone with their bosses number, other groups such as giovanni , tzmisce mansion and the police will get their chief numbers eventually.
Dealer stands in a neutral position and only had the Baron number, now they can call the other faction and make DEALS.
I always thought that the archivist had their boss number, i was wrong so it was added to them and the supply tech, having the number of your boss is always good.
:cl:
fix: The Tremere Regent contact info not triggering auto
fix: The chance that an important is added without their name
add: Archivist and supply tech now get their bosses in their contact list
add: Add the Dealer contacts to the Prince, Sheriff and Seneschal
add: …
> Small Bug fixes for phones and a small update for it as well.

- code/modules/mining/machine_vending.dm
- code/modules/wod13/food.dm
Adds a police vendor with multiple items - cameras, recorders, white crayon, handcuffs, body bags, evidence box and multiple others. To use it, click the vendor with a police badge, then it will add 12 points to the vendor. This can only be done once every 2 minutes to prevent abuse. Likewise, money can't be taken out of this vendor, nor be added.
PR'd code-wise, will have to be added on the map after to avoid PR conflicts.
Gives the police some QoL
:cl:
add: Added a police vendor
/:cl:
> Adds police vendor to the PD

- code/modules/wod13/wallcode.dm
Renames shit to sewage.
Sewage is more fun to tread through than shit! (why was sewage named 'shit' in the first place? russians ig)
:cl:
tweak: changed the descriptive name of 'shit' tiles to 'sewage'
/:cl:
> Renames the sewer's "shit" tiles to be "sewage"

- code/modules/vtmb/electronics/phones/phone.dm
[Compiled Tested and tested ingame]
Really stupid oversight that i thought that it was fixed, since i never tested readying from the round start, now finnaly if you roll prince, sherif etc from round start your contact will appear fine and with the name.
Fix
:cl:
:fix: Fix owner recieving their name too late, when it was added to the glob it was empty.
/:cl:
> [HOTFIX] Important contact not existing if someone rolled that role from roundstart

- code/modules/vtmb/vampire_clane/clane.dm
It was reported to me that somehow being embraced by a nosferatu could trigger the embraced being tped to the nosferatu town, i tried replicating that on my debug server and was unsucessful but there are indeed some bugs that don't happen on the debug and that could be one of those.
When a vampire joins the game their roundstart_vampire is set to true, it is set to =  false for non vampires and it is set to false too when someone is embraced, now it checks if someone was embraced mid round  and if they were, they can't trigger the tp proc.
Fix
:cl:
fix: Add a check if the vampire is a roundstart(it includes late join) vampire or not .
/:cl:
> Fix the chance that being embraced by a violating appearance clan to spawn you in the nosferatu town

- code/modules/mob/living/blood.dm
- code/modules/reagents/chemistry/reagents/other_reagents.dm
- code/modules/vtmb/magic/pyramid.dm
- code/modules/wod13/food.dm
Adds the Bloodwalk ritual that allows you to tell someone's generation and clan. Also adds syringe boxes to the pharmacy for 300 dollars each, and slightly buffs teleport by reducing the requirements to regular bloodbags.
Expands on the core features of Tremere that are sorely lacking.
:cl:
add: Added blood walk ritual
balance: rebalanced teleport ritual
/:cl:
> Bloodwalk ritual

- code/modules/vtmb/gamemodes/bloodhunt.dm
- code/modules/wod13/special_shit.dm
Simple change that makes the bloodhunt display it's author to everyone, so that everyone knows if it's the prince or some random human using the skull.
It's good for both admins and people to know in case someone abuses it.
:cl:
tweak: tweaked blood hunt announcement
/:cl:
> Makes bloodhunt name the author

- code/modules/client/preferences.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/human/species_types/humans.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defines.dm
- code/modules/projectiles/projectile.dm
- code/modules/surgery/organs/vocal_cords.dm
- code/modules/vtmb/archetypes.dm
- code/modules/vtmb/disciplines.dm
- code/modules/vtmb/ghoul_species.dm
- code/modules/vtmb/kindred_species.dm
- code/modules/wod13/car.dm
- code/modules/wod13/doorcode.dm
- code/modules/wod13/lombard.dm
- Archetypes will now feature text that says what their actual bonus ability is.
- Bonus attributes will now be visible on the character screen and when checking your own stats.
- Fixed a bug where the Dude archetype did not actually work in affecting ranged weapon critical chances. It will now properly provide +3 Cruelty to critical damage calculations.
- Fixed a bug where the Cruelty attribute's upgrade cost text didn't reflect its proper cost, which was supposed to be doubled.
- Reworked some backend stuff to make a few bits of the attribute system more modular and reduce copypaste. The system will now support displaying more than 5 dots on the character menu.
- Added support for bonus attributes; dexterity, lockpicking and athletics can now also benefit from the system, but currently …
> Tiny changes

- code/modules/wod13/lombard.dm
Fixes a bug in #394 that would make items sell for FAR less independent of the user's social score due to an order of operations bug. Instead of user.social + user.additional_social * 0.1, it was doing (user.social + user.additional_social) * 0.1.
Bug fix so you can sell things for actual money again.
:cl:
fix: You can now sell items for normal prices again.
/:cl:
> Fix selling price bug

- code/modules/client/preferences.dm
Increase the number of save slots from 10 to 20, 50 took too much of the screen so i lowered.
20 Slots:
50 Slots:
The people want it , i also agree that 10 is too low.
:cl:
tweak: changed the number of save slots from 10 to 30.
/:cl:
> Increase the number of max save slots.

- code/modules/wod13/bloodsucking.dm
Made the "you sip some blood from your victim" message not initially show up before actually sucking any blood from the victim.
Fixed a bug where you could repeatedly start the blood sucking process on a vampire, which would automatically heal you somewhat without even actually sucking any blood.
> Blood sucking fix

- code/modules/vtmb/magic/pyramid.dm
In the context of roleplay, Clan Tremere is not a fun experience. They inherently lack any niche or the ability to be feared as they are in lore. Giovanni/Cappadocians/Kiasyd can summon ghosts and Tremere can as well, and Lasombra get more utility out of their shadow magics so with that said, to give the Camarilla something to make people fear Clan Tremere.
I have swapped damage types from fire (which can easily be bloodhealed I would add) to aggravated damage. The damage might need to be scaled down post-generation nerf but I think its a good start to let Tremere Do Their Thing.
Mentioned Above
:cl:
Makes curse deal cloneloss damage.
/:cl:
> Makes Curse an actual curse

- code/modules/admin/admin_verbs.dm
- code/modules/vtmb/gamemodes/masquerade.dm
New admin verb for a better manupilation of the masquerade, now it is also triggering the subsystem effects correctly like the  npc SWAT getting called on all kindred once it hits <250, also the global messages about the masquerade.
Masquerade now can't go over 1000 too
Masquerade won't freeze anymore if an admin wishes to change, fixes it going 1000 and all effects trigger like it should.
:cl:
add: New admin Verb
fix: Masquerade going over 1000
/:cl:
> New Admin Verb to Change the Global Masquerade(So admins can't accidentally freeze it by doing manually), Fixes Masquerade going over 1000

- code/game/objects/items/devices/radio/radio.dm
Except inside Penumbra.
This is so that going up a building's roof does not completely bust your radio signal to the Camarilla prince.
Not sure if there's a better way to code it without hardcoding the specific z-level values on which the levels are on.
> Radios will now work between most zones

- code/modules/vtmb/kindred_species.dm
After being transformed into a vampire/ghoul, now you can pick between "Yes" or "No" to save that change on your slot, keep in mind that WL clans for those without the WL, will be changed to their non WL versions or randomized.
For power gaming reason, if your sire is below the 13 gen, you will always be a 13th gen as well, if they are 13th gen you will be turned into a Caitiff 14th gen but unfortunately the game by default will force the 14th gen to turn 13th on the char slot.
On a side note for coders, create_disciplines does not work if you pass a list, i tried a couple of time to fix but it was not my focus so i used give_discipline directly, that also means that gargoyles created ingame don't recieve their disciplines.
Vamp choice:
Ghoul choice:
This is mainly for rp reasons, so …
> Add a choice to keep being a vampire after a embrace or after being turned into a ghoul

- code/modules/vtmb/electronics/p25.dm
- code/modules/vtmb/jobs/police.dm
- code/modules/wod13/food.dm
dead can no longer speak in p25 anymore, police no longer spawn with outdated radios.
hotfixes, more coming soon
:cl:
fix: Dead can no longer speak through p25 radio; Police no longer spawn with outdated radios.
/:cl:
> Hotfixes pt. 1

- code/_globalvars/lists/mobs.dm
- code/controllers/subsystem/humannpcpool.dm
- code/modules/admin/view_variables/admin_delete.dm
- code/modules/vtmb/npc/beastmaster.dm
- code/modules/wod13/npc_movement.dm
Adds a pool for living npcs only, makes it so they properly get removed from said list if they die and makes the respawn feature work as it should be. Also makes it so admins deleting npcs actually removes them from the pool.
It fixes some NPC problems
:cl:
fix: fixed a few NPC related issues
/:cl:
> npc pool fixes

- code/modules/wod13/narco.dm
Problem: Growing weed is a pretty bad alternative to just fishing. In fact, making drugs generally has a lot more problems than just fishing.
Partial solution: Shorten the time it takes to sort weed (and also make blunts) to just 1 second from 5.
> Makes sorting and rolling weed 5x faster

- code/modules/vtmb/kindred_species.dm
Ghouls were locked out of all unique Disciplines due to an oversight when locking whitelisted Disciplines to people with that whitelist.
Let ghouls have fun for once.
:cl:
fix: Ghouls can have unique Disciplines again.
/:cl:
> Fix ghoul Discipline bug

- code/__HELPERS/game.dm
This includes Question To Ancestors, summoning demons and creating gargoyles.
Why? Because Auspex ghosts aren't real ghosts! They aren't supposed to be polled for midround roles, and doing so prevents them from returning to their bodies.
> Auspex ghosts should no longer be polled for midround roles

- code/datums/components/crafting/crafting.dm
Small change. No more random deciseconds of extra time until the UI updates. Most noticeable with low-crafting-time items like sorting weed.
> The crafting UI will now update as soon as an item finishes crafting

- code/modules/vending/boozeomat.dm
It makes alcohol free in all boozeomats.
It was annoying to have access through id cards. Now it's convenient.
:cl:
tweak: boozeomat is free
/:cl:
> Make booze free

- code/modules/mob/living/carbon/human/human.dm
This PR makes the movement slowdown scale with the user's max health, so that relatively minor injuries no longer slow down as hard as they should.
Obvious balance implications in the way that high-physique characters and lower-generation vampires can move during combat, however.
This also fixes a potential issue where high-health characters could be slowed down far more than lower-health characters because of how the slowdown calculation worked, which didn't scale with max health.
> Injury slowdown will now scale with the user's max health

- code/modules/vtmb/electronics/atms/atm.dm
Gives non-fabulously rich characters a little extra minimum money, in return for having a lower ceiling on how much they can have round-start.
Allows for buying fashion accessories at round start and other near-necessary items.
> Decrease Variation in Round-Start Account Balance

- code/modules/surgery/organs/ears.dm
- code/modules/surgery/organs/eyes.dm
- code/modules/surgery/organs/heart.dm
- code/modules/surgery/organs/liver.dm
- code/modules/surgery/organs/lungs.dm
- code/modules/surgery/organs/stomach.dm
- code/modules/surgery/organs/tongue.dm
- code/modules/wod13/food.dm
- code/modules/wod13/narco.dm
The following pr makes it so the total cost of one NPC is roughly 2K if you trade in every single organ (Going by the cost = value). This PR also significantly buffs drug selling and weed trading as well! Encouraging players to set up farms and defend them as a means of establishing territory.
As mentioned above.
:cl:
Lowers the value of all organs to equal 2K.
Increases the value of weed to 350, meth to 650, and cocaine to 750.
/:cl:
> Readjusts values & lessens the amount of corpsed bodies

- code/datums/datacore.dm
The manifest will now list Camarilla, Primogen, Tremere, Anarch, Giovanni, Old Clan Tzimisce, Law Eforcement, Warehouse, Triad, and Misc, in that order.
It beats listing everything as either Command (Camarilla), Science (Anarch) or Misc.
:cl:
fix: The Manifest now actually uses our job groupings.
/:cl:
> Changes the manifest Groupings

- code/modules/client/preferences_toggles.dm
For some reason someone commented out being able to disable ghost ears? This removes the uncommenting so you can turn off ghost ears if you don't want to hear everyone in the world all the time no matter what.
:cl: Bisar
fix: you can now turn ghost ears off.
/:cl:
> Fix ghost ear toggling

- code/modules/wod13/narco.dm
The original PR I made for this was a bit too overtuned; I've since rectified this with this PR here. Fewer people are of the dreaded "path of the organ harvester" so that worked at the very least! Anyway, heres the math:
350 x 4 (meth) for 1400, 
An epi bottle is 200 dollars (vendor price)
Potassium iodide is 100 (vendor price)
Gasoline canister is 250 (vendor price), but I misread the code, its now taking up 100 out of 1000 so you are really only going to get 10 batches of meth.
Adding it together, each batch at the cost they are sold for will yield a profit of 850 per batch and making 10 of it is 8500 but this requires significant cost investment, unlike weed which requires roughly 15 minutes to grow from round start.
150 for weed, previously 50. 
You'll generally hit 900 dollars if …
> Adjusts drug money for a final time

- code/modules/mob/living/carbon/carbon.dm
A bug was introduced in the Kuei-jin PR where, for some reason, Torpor code was copy and pasted with no regard for the fact that it was an if/else. This broke torpor for Kindred while letting it work for Kuei-jin. This PR removes the copy and pasted code to let it work for both.
The bug is annoying and disables a fun feature.
:cl:
fix: Torpor works for Kindred again.
/:cl:
> Fix Torpor bug

- code/controllers/subsystem/job.dm
- code/modules/vtmb/jobs/dealer.dm
After a conversation about a lack of roles for KJ, I gave it some thought and looked at dealer and thought it would be interesting to let Garou be a wise-guy glasswalker and run the warehouse, or let a black spiral try to start a drug ring within the warehouse too.  So this PR effectively makes the warehouse a wild card and its own power through economic might which seems to be the way of things moving into the future.
Round diversity is, mostly, the number one goal here. The fact that the warehouse isnt guaranteed to be Camarilla aligned will allow more inter-round diplomacy and even the allowance of gimmicks on an easier scale, like a glasswalker dealer of the wise-guy camp.
:cl:
Add: Allows werewolves & wk to be a Dealer.
Changes: The job text when you join.
/:cl:
> Expands what splats dealer can be

- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/human/species_types/golems.dm
- code/modules/mob/living/carbon/human/species_types/monkeys.dm
- code/modules/mob/living/carbon/human/species_types/mushpeople.dm
- code/modules/mob/living/carbon/human/species_types/synths.dm
- code/modules/wod13/mannequin.dm
Revival of #397 , this PR does two things:
1. It toggles the "gentle" variable to Potence's throw_impact, which disables damage and stuns taken from colliding with other things such as walls.
2. It reworks the punching knockdown system. Previously you needed Potence to have a chance to knock someone down (until higher levels of Potence would just be guaranteed to knock down and stunlock), now punching has a 10% chance per punch to knock someone down for 2 seconds, which increases up to 30% per punch depending on the difference between the puncher's physique and whichever is greater of the target's physique or dexterity. The difference for the stun chance increase has to be at least 2 (example: user's physique of 5 vs target's physique and dexterity of 3, which increases the stun chance to …
> Potence nerf and an unarmed combat change

- code/modules/research/techweb/all_nodes.dm
On research subsystem firing/initializing it would go through design_ids to see if there were any invalid or null ones, this one was throwing a runtime on master because #595 accidentally left it in which caused a runtime on running the server.
Runtimes? BAD!
Less runtimes, less problems, more development.
> Fixes roundstart runtime issue.

- code/datums/json_savefile.dm
- tgstation.dme
See title
Ported from the github repository tgstation/tgstation, co-authorship sourced from commit logs for (as of 1/24/2025 10:16PM ) code/datums/json_savefile.dm
The ability to delete thousands of lines of shitcode that serves only to load characters and check character attributes.
:cl: Bisar
add: Savefiles (such as all the stuff arbitrarily saved in prefs) can now be turned into json savefiles.
code: Added json savefile support
/:cl:
> Port json_savefile from /tg/ to turn character sheets and prefs into json for some sanity

- code/datums/json_savefile.dm
Fixes a compilation error currently on master related to json_encode's 2nd argument that was introduced in 515.1590
The server can update
:cl:
fix: No more 514 compilation error related to json_encode
/:cl:
> Fix JSON compilation error

- code/modules/wod13/map.dm
Removes the duplicate triad soldier outfit and makes the ghost spawner role use the roundstarting outfit.
Testing:
- Launch the San Fransisco map
- Observe > Ghost > Spawners Menu
- a triad soldier (23 left) > Spawn
- Check the LANG menu on the left
- Check the backpack for the extra balaclava and knife
Bugs bad, this was reported on Discord
fix: Fixed triad soldiers spawning via the ghost spawner not speaking Cantonese. They now also spawn with an extra balaclava and a knife as the roundstart ones.
> Fixes ghost spawning triad soldiers not speaking Cantonese

- code/modules/surgery/organs/lungs.dm
Removed diseases from rotten corpses and organs, cuz it doesn't add anything to the gameplay and all diseases require reagents that we don't have
Removed it without commenting as we're getting rid of athmos soon anyway
directly removed miasma sickness
> Removed diseases from rotten corpses and organs

- code/modules/wod13/cargo.dm
- code/modules/wod13/food.dm
Fixes an oversight from my last PR. The sorting of the vendors caused me to remove the seeds and bailers so now you can get them. Also it sorts the Cargo Vendor from lowest to highest by category & lets magazines be ordered in bulk so you have reason to go to the Dealer too. Silver & Incen cost isn't touched though.
Fixes oversight, less extensive charging.
:cl:
Readds bailers and seeds to the BMD
Makes them orderable too
Sorts the Dealer Cargo Terminal
Makes it so you get more magazines in bulk cost
:cl:
> Fixes Oversight & Makes more things orderable at the Dealer

- code/__HELPERS/unsorted.dm
Turns a lengthy if-else chain in /proc/parse_zone into a switch, this proc is usually used to get the name for body parts, specifically to translate the define names of them to more common words for them.
(Reference for what the defines are and why things like head & mouth & torso are not included since they get spat out at the else end)
Image of it working in game (as you can see the body parts are named right leg and left leg and so on instead of r_leg and l_leg)
Runtime present in screenshot is from master itself and unrelated to this PR.
Efficient code! That is good and looks pleasant! Yes!!
Not needed, purely code efficiency related.
> Gets rid of lengthy if-else chain in parse_zone() proc

- code/modules/wod13/narco.dm
Straightforward, so you know when it is in need of a refill.
> Examining the bailer will now tell you how many times it can water.

- code/__DEFINES/cooldowns.dm
- code/datums/emotes.dm
- code/modules/mob/living/carbon/human/emote.dm
No matter the source, the audio check for emotes always failed. This PR (attempts to) fix audible emotes (currently, scream only).
I added a default 10 seconds cooldown between audible emotes and a variable for the scream emote itself. These can be tweaked later when we add other audible emotes (like werewolf growling, etc) and a potential delay bypass. I stepped over it with the debugger many times, but it might still not be perfect, say code is daunting.
Tested it by:
- Spawning in as female garou, *scream
- Spawning in as vampire, set gender to male, *scream
- Punching NPCs to hear them scream
https://github.com/user-attachments/assets/600186b9-691d-41b3-a5af-f25af2df0e16
Bug bad, fixes this report:
:cl:
fix: The scream emote is audible now, both by players and NPCs.
/:cl:
> Fixes the screaming emote audio not working

- code/modules/admin/admin_verbs.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/human/death.dm
Removes all times ghost vision is set to or animated towards CMNoir greyscale-o-vision.
Keeps the CMNoir color matrix list incase of future use.
Gif of it not greyscaling your screen when you ghost
To be admittedly rather brash, the greyscale vision just makes observing worse, it doesn't add any flavor or theme or any other since of aesthetic but rather wears and tears on your eyes as you try to look at the cool stuff thats happening through a faded lens. Best case it's a nuisance and makes any recording of in-game footage from a ghost/observer perspective hard to look at and at worst it just drives people away from staying to observe or atleast be more interested in a game they're not directly participating in.
:cl: Vondiech/Citruses
del: Ghost greyscale vision is no more.
/:cl:
> Removes all times CMNoir/greyscale-vision is set for ghost

- code/modules/vtmb/jobs/jobs.dm
- code/modules/vtmb/jobs/primogen.dm
In line with the Counsel of Primogen sourcebook for VtM, I have provided the Primogen with three badges in their backpack starting kit.
**Primogen's Myrmidon Badge**
A Myrmidon is the personal bodyguard of a Primogen, responsible for their safety and security, as well as breaking legs when needed.
**Primogen's Steward Badge**
A Steward is responsible for maintaining, stocking, and staffing the Primogen's domain/haven, hosting guests, etcetera.
**Primogen's Whip Badge**
A Whip is a Primogen's equivalent of a Seneschal, handling all of the personal affairs of the Primogen delegated to them, and often representing the Primogen at lesser functions.
The Primogen presently lack any structure to support maintaining a 'team' of confidants/staffers, which is extremely common for them to do in the …
> Provides the Primogen with badges for Primogen Staff

- code/controllers/configuration/entries/general.dm
- config/config.txt
- interface/interface.dm
Our wiki was moved both domain- and engine-wise, so both the links and the search path had to be updated.
To test:
- Boot up the server
- Click "Wiki" on the top-right
- Search for something, click Ok
- Leave it empty, click Ok
The ingame wiki link does not point to the wrong wiki site.
:cl:
config: The ingame wiki link has been updated to point to the new wiki.
/:cl:
> Updates the ingame wiki link

- code/modules/projectiles/projectile.dm
Turns out it would reset the damage back to the initial value multiplied by 2, which messes with 3 different guns that have damage multipliers (snub-nosed revolvers, sniper rifles and the semi-auto shotguns). This fixes it.
> Cruelty will now respect gun damage multipliers

- code/modules/vtmb/vampire_clane/ventrue.dm
The Ventrue don't spawn with their keys, this fixes (??) it. Unless it was intended that only the Primogen can open doors for their entire clan (in that case, please close this).
Spawned in as a Ventrue Prince (got Prince keys + Ventrue keys), then spawned in as a Ventrue Citizen:
The Ventrue have their own haven, but they cannot access it without the Ventrue Primogen being a doorman for them.
:cl:
fix: The Ventrue now spawn with their clan keys.
/:cl:
> Adds ventrue keys to ventrue characters

- code/modules/mob/living/carbon/carbon_say.dm
People were accidentally invoking the say verb twice, creating multiple overlays when the code is only capable of cutting the last one
Hi metek
:cl:
add: Speech bubble no longer gets stuck
/:cl:
> Speech bubble overlay no longer gets stuck on

- code/modules/wod13/bloodsucking.dm
You no longer get reset to generation 13 by diablerie, as this is an extreme tool to allow (hypothetically) just about anyone to use on anyone they can robust. 
In addition, diablerie now simply lowers your generation by 1 on a successful attempt **(edit: when performed on someone of a lower generation),** or by 2 if the victim was at least 4 generations below you. _Failed_ diablerie raises your generation by 1.
The server is getting rid of many of the progress-loss features the codebase once had, and I think this is appropriate for that direction. The possibility of losing 10+ hours of XP after losing a fight might have suited what the original server was going for, but not this one, and it's not practical to effectively moderate every single use. 
This may even make diablerie more …
> Nerfs diablerie

- code/modules/wod13/npcroles.dm
When a rat is not "in view" of anything it deletes itself to not cause mass-rat-event.
If you pick a rat up, it is not "in view" and deletes itself, but the mob-holder code will still have it in your hand or in your bag until you decide to drop it in which case it runtimes, because forcemove is given a null destination, and then deletes the rat.
This adds a check so that, if the rat is technically not anywhere, the rat won't be deleted inside things like crates or backpacks.
Also changes oviewers to viewers so that it won't try to delete itself if its viewed by the person holding it.
Added a check for if the rat is controlled by a client (like with current animalism 5) in which case we don't want to delete it suddenly.
Credits for the help needed to identify, diagnose, and patch this …
> Fixes rat-caused runtime which means you can store and throw them from your hand again & Animalism 5 fix.

- code/_onclick/click.dm
- code/modules/mob/living/carbon/human/species.dm
Problem: You can't ctrl+click on rats to put them in aggressive grab mode, you have to be on grab intent and to manually click them.
Solution: This PR.
Also relaxed a check so that it allowed for simple-mobs to be aggressive-grabbed through ctrl+click, this also means you can incorporate martial arts on simple-mobs via click-dragging rather than grab intent only.
> Click-dragging simple-mobs such as mice should now properly allow aggressive grabs

- code/modules/vtmb/vampire_clane/kiasyd.dm
These two abilities are supposed to disorient another persons hud, either from casting myth 4 on them or from being caught in a spin trap, however if they don't have a client, like NPCs or simple_mobs, they don't have a hud and this then throws a runtime when they are caught in these. Adds checks for both to make sure that the code only triggers when someone with a client (and therefor, a hud) is targetted.
Runtimes are stinky and complicate things
Yet another runtime cleanup, nothing of note for players to know or care about.
> Mytherceria disorient runtime fixes

- code/modules/vtmb/dharma.dm
This adds two new dharmas to the game:
The Diamond Serpents  (from The Relentless Ages Book)
Face of the Gods
Along with removing the dharmic rise and fall mechanics currently ingame as previously requested by Metek.|
Further fleshes out the dharmas for Kuei-jin, along with adding one of the revised books custom dharmas and another heretical path dharma.  
:cl:
add: Two New Dharmas
del: Removed the originally requested rise and fall code plaguing dharmas
> Dharmic Adjustments/Additions

- code/modules/mob/mob_say.dm
I was experimenting with winset to make using the tab typing bar more ergonomic and I ended up fucking merging it
please don't tell anyone you saw me do that.
it's not supposed to be there
:cl: Bisar
fix: removed testing code that got put into production
/:cl:
> Hotfix removal of a testing thing I left in like a chump

- code/modules/mob/living/carbon/werewolf/transformation.dm
- code/modules/vtmb/werewolf/gifts.dm
Currently switching out of Glabro sets your Physique to 1. This is because it sets Physique to its initial value which is always 1. This PR makes it so switching out of Glabro instead lowers Physique by the same amount it's raised.
I tested both the bug and confirmed it is real, and tested this fix.
One of the Werewolf forms just setting your Physique to 1 when you leave it isn't the intended experience I'm pretty sure.
:cl:
fix: Leaving Glabro no longer sets your Physique to 1.
/:cl:
> Fixes Glabro Physique

- _maps/map_files/Vampire/SanFrancisco.dmm
- _maps/map_files/Vampire/runtimetown.dmm
- code/modules/wod13/doorcode.dm
Fixes the police chief door being invisible as it was not a glass door subtype.
https://github.com/user-attachments/assets/ccb85e1a-5ef0-424f-a0b1-514845e89be4
It is visible now.
Fixes the Police Chief's door being invisible.
> Fixes the Police Chief's door being invisible

- code/modules/client/preferences.dm
- code/modules/mob/mob_say.dm
So, funny thing. Besides setting your flavor text in your character setup menu, there was for some reason a copy pasted verb that let you do the same thing but without any HTML stripping. This led to people putting images and videos in their flavor text.
No more HTML injection and possible bad stuff.
:cl:
fix: Removed flavor text verb.
/:cl:
> Fix flavor text exploit

- _maps/map_files/Mining/Lavaland.dmm
Fixes the lack of a properly var'd teleport marker in the Umbra causing BSD Theurges to be unable to reach the Umbra.
https://github.com/user-attachments/assets/6d73b0bd-acb0-4acd-8816-853e0dfa8fe4
Let's BSD Theurges do what they should be able to. Prevents BSDs from having to awkwardly use other totems.
:cl:
fix: Adjusts the teleport marker's Tribe Var for the BSD's to properly reference their Tribe name.
:cl:
> Fixes BSD Totem Portal Marker

- code/modules/wod13/ambient.dm
#717 missed an / when defining an area, compiled and worked as usual just a small thing that makes it throw up a warning about relative pathing
less compiler complaints more actual compiler problems solved
the smallest code-related thing imaginable for a PR,
> Someone missed an / here!!

- code/modules/wod13/narco.dm
The weed trays and drug labs will now tell you if you anchor or unanchor them.
The weed trays and drug labs can no longer be telepathically anchored or unanchored.
Removed "the the" cases for weed trays and drug labs.
Fixes and responsiveness.
:cl:
add: The weed trays and drug labs will now tell you if you anchor or unanchor them.
fix: Fixed weed trays and drug labs being able to be telekinetically anchored or unanchored from a distance.
spellcheck: Removed "the the" cases for weed trays and drug labs.
/:cl:
> Weed tray and drug lab tweaks

- code/game/machinery/recycler.dm
Makes the recycler no longer delete itself. This is most notable with the recycler in the restaurant's basement.
It makes the recycler reusable rather than cause it to magically disappear.
:cl:
fix: The recycler in the restaurant's basement will no longer delete itself upon shoving someone in it.
server: something server ops should know
/:cl:
> Recycler no longer deletes itself

- code/modules/client/preferences.dm
- code/modules/client/preferences_toggles.dm
- code/modules/wod13/verbs/dice.dm
Improves the storyteller roll to have better big O complexity
Checks if people passed through roll_viewer are actually in possession of a client
Makes the preference option for toggling rolls exist; was deleted in a bad merge
uh, roll good, add rolls to all things pls, thx
:cl:
add: Readded the preferences toggle for storyteller rolls
qol: optimized the storyteller's roll code
fix: Fixed runtimes occurring when rolling against an NPC
/:cl:
> reroll the roll code

- code/modules/wod13/npcroles.dm
What are Russians on? Is it something in the water? Why do humans mutate to do this shit?
https://www.youtube.com/watch?v=6zkL91LzCMc
:cl:
fix: Now not everyone is white! Just like we drew up.
/:cl:
> De-Racisms a lot of the NPCs 2

- code/modules/mob/living/carbon/human/examine.dm
It compiles, I examined the pink haired guy on a character without charmer, no blush. 
The blush is really fucking annoying.
:cl:
del: Blush no more.
/:cl:
> Removes blushing from Charmer

- code/modules/client/preferences.dm
Gives ~~Garou~~ all players 3 quirk points to work with at character creation/change appearance, the same as humans. ~~Presently, Garou are almost entirely unable to take quirks that are very beneficial for roleplay (dancer/languages) without making their character essentially disabled, as 90% of the negative quirks are vampire restricted.~~
~~Garou~~ Everyone deserves to speak other languages without missing an arm or being blind or walking at snail speed.
:cl:
add: Gives everyone 3 quirk point balance at character creation/change.
:cl:
> Gives Everyone 3 Quirk Points

- code/__DEFINES/traits.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/mob/living/living_defines.dm
- code/modules/projectiles/ammunition/_firing.dm
- code/modules/projectiles/gun.dm
- code/modules/vtmb/archetypes.dm
Changes the Gunfighter archetype's delay reduction from "basically no delay between shots" to "halved delay".
Slightly reworks the code so that it uses a trait instead of a variable.
It's somewhat more balanced. Rapid fire guns will still fire very fast but they should no longer literally fire like shotguns. Also makes sure the [buffed sniper rifle](https://github.com/WorldOfDarknessXIII/World-of-Darkness-13/pull/607) does not become OP (its main drawback is a 4 second delay between shots which gets removed with Gunfighter).
:cl:
balance: The Gunfighter archetype now only reduces firing delays by half instead of removing them.
/:cl:
> Gunfighter now only reduces delay by half instead of removing it

- _maps/map_files/Vampire/SanFrancisco.dmm
- code/modules/wod13/doorcode.dm
creates techshop keys as a item rather then a  map edit.
lets glasswalkers potentially spawn with em and lets admins spawn more in.
:cl:
added techshop keys as a item.
:cl:
> Techshop keys

- _maps/map_files/Vampire/SanFrancisco.dmm
Builds on #715 that was nuked in the rebasing process. I could not reach the contributor for weeks and they missed some bloodpacks, so I'll just fix it myself and attribute it to them
These bloodpacks were the epitome of "if you dive into the game files, you get overpowered stuff". They had no ingame indicator that they refilled 1.5x the full blood pull of a gen7 vampire's. silliness
<details>
they do be no longer here
</details>
:cl: Miraviel, xxxnoscopexx:
del: Removed some nonsensinal 40 BP-refilling bloodpacks from the map.
/:cl:
> Removes the few 40 BP bloodpacks from the map

- code/modules/client/preferences.dm
"OCCUPATION CHOISES"
Fixes a single spelling mistake in the character customization menu which I spotted not even 4 minutes into my first time playing this server.
Good spelling makes for a good first impression. Proceed to ignore all spelling mistakes I make while filling out this form.
<details>
<summary>Where's the testing?</summary>
I changed a string. Actually downloading the ENTIRE codebase and running it on my geriatric machine seems a bit overkill for _something so minor and programmatically insignificant._ **If I have to, though, I will.** But for right now, I'm pretty sure this'll work.
</details>
:cl: TiberianEuan
spellcheck: fixed a typo "occupational choises"
/:cl:
> Corrected a single spelling mistake in the character setup menu.

- code/modules/wod13/doorcode.dm
Adds clerk access to the sheriff keys, so they can access the receptionist.
They cannot access some areas of the Tower and as the de facto head of security, this should not be the case (they already have prince access).
<details>
</details>
:cl:
fix: Fixes the Sheriff not having access to certain doors in the Millenium Tower.
/:cl:
> Fixes the sheriff not having access to seneschal doors

- code/modules/wod13/clothcode.dm
This PR allows the following items to be worn on vests and its subtypes:
- flashlight
- baton
- handcuffs
- ID/badges
Adds (mainly) police vests extra functionality.
<details>
</details>
:cl:
fix: Vests can now hold the following items: flashlight, police baton, IDs, handcuffs.
/:cl:
> Fixes vests not holding anything in the suit storage

- code/modules/flufftext/Hallucination.dm
When you get set on fire from the fire hallucination, you get 0.1 fire stack.
This does not go away after the hallucination is done, so all malkavians walk around "covered in something flammable".
With this, the stack goes away with or without putting yourself out.
Detecting Malkavians won't be as easy as shift-clicking them.
<details>
</details>
:cl:
fix: The Malkavian fire hallucination no longer has lingering fire stacks, meaning Malkavians won't have the "covered in something flammable" examine text for the whole round.
/:cl:
> Fixes hallucination fire stacks lingering

- code/modules/wod13/wallcode.dm
The spectre of Flavcode haunts our codebase perpetually. One of them is ocean turfs being open but also preventing things from entering them but only sometimes.
Instead I just made the damn things dense pending a complete rework of how we move in water instead of the snowflake crap we deal with now.
There's inconsistent behavior with what can enter ocean turfs and there's really no reason to be able to enter them right now, considering there's like, nothing out there. Until we actually need them, having them be dense gives admins and players one less stupid thing to deal with.
<details>
https://github.com/user-attachments/assets/dcd30ec8-0956-49d5-8399- …
> Ocean turf hotfix: They're dense now

- code/modules/wod13/npc.dm
- code/modules/wod13/npc_aggression.dm
- code/modules/wod13/npc_movement.dm
- code/modules/wod13/npcroles.dm
- NPCs Now only drop their weapons items on death
- NPCs do not aggro at first when being hit by attacks below a certain threshhold 
- NPCs do not aggro at first when items below a certain throw force are thrown at them
- Simplified parts of the NPC AI code so it will be easier to rewrite in the future
NPC's are too easy to kill and too easy to rile up. This will make them slower to anger and scarier when angered.
https://github.com/user-attachments/assets/dd6432e6-0400-4ffc-89e8-ca5f040d2b88
:cl:
balance: NPCs Now only drop their weapons items on death
balance: NPCs do not aggro at first when being hit by attacks below a certain threshhold 
balance: NPCs do not aggro at first when items below a certain throw force are thrown at them
refactor: Simplified parts of the NPC AI code so it …
> NPC AI fixes (NPC's drop weapons less, are 50% less psychotic)

- code/modules/vtmb/vault/vaultdoors.dm
Fixes vault doors not having their opacity set to TRUE whenever they are closed, and fixed vault doors being impossible to open or close when you move away mid-closing or mid-opening.
Fixes things.
<details>
</details>
:cl:
fix: fixed a few vault door bugs
/:cl:
> Vault Door Fix

- code/modules/wod13/structures/doors/vampdoor.dm
Makes it so that only doors with lock perms can be locked with lockpicks
Trolls have been going around locking doors with lockpicks for fun. 
<details>
https://github.com/user-attachments/assets/f507b9b7-aa42-4b3f-aafc-08fca2f3d386
</details>
:cl:
qol: lockpicks can only lock doors that lock
/:cl:
> Troll-proof lockpicking

- _maps/map_files/Vampire/SanFrancisco.dmm
This PR fixes a poorly mapped corner in the caves of NosTown that left a visible matrix, as well as fixing the Clinic Garage door to have the appropriate ID, so it should no longer be linked to the Pentex Executive's button :)
Matrixes being randomly visible is frowned upon. Pentex owning the Clinic Garage Door makes little sense (and was an oversight of the Endron mappers).
These are extremely minor changes, but let me know if you think it is essential I provide a loaded in view of them.
<details>
</details>
:cl:
map: Fixed a visible matrix in Nos Town.
map: Fixed the Clinic Garage being linked to Pentex Executive access.
:cl:
> Fixes a Visible Matrix in NosTown and the Clinic Garage Door Access

- code/datums/keybinding/human.dm
This change lets Salubri with the Iron Gullet trait feed off of dead humans.
It's pretty nonsensical for corpses to be considered "aware" targets for Salubri feeding.
<details>
https://github.com/user-attachments/assets/88f9c4ec-eeca-4e3e-980e-ce9cbc50d5d3
</details>
:cl:
code: The dead are no longer "aware" for the purposes of Salubri feeding.
/:cl:
> Let Salubri with Iron Gullet feed on corpses

- code/modules/wod13/cargo.dm
Two warnings were introduced as a result of someone forgetting to put slashes before their type declaration, and they accidentally made the AE desert eagle order say it orders three boxes while it actually orders two. This gets rid of the warning and makes it actually order three boxes.
No parser warnings = life is good.
<details>
</details>
:cl:
Fixed parser warning from the cargo PR.
Made the Desert Eagle 3 AE ammo box order actually order 3 boxes.
/:cl:
> Fix new cargo code warning

- code/modules/wod13/cargo.dm
Reduced the drug lab's cost from $10000 to $4000.
The drug lab is extremely expensive and takes way too much luck to make up for its cost compared to something like selling green packages. It also locks anyone who doesn't have at least Social 5 in it away from making any sort of long-term profit. Very unprofitable, mainly due to its steep initial cost, which this PR reduces.
:cl:
balance: The drug lab's price is now $4000 instead of $10000.
/:cl:
> Reduces drug lab cost by 60%

- code/modules/wod13/quirks.dm
Properly removes the Diablerist quirk from the game, which showed up as "Test Quirk" in the quirk menu.
It did not have any permanent consequences, it merely marked the character as a diablerist for the duration of a round.
It's a bugfix. It was intended to be deleted months ago.
:cl:
fix: Properly removed the Diablerist quirk from the game.
/:cl:
> Properly removes Diablerist quirk

- code/modules/client/preferences.dm
- code/modules/vtmb/dharma.dm
Previously, Kuei-jin had to spend 20 XP for each Dharma level. This PR changes that cost to 5 XP per current level to a maximum of 20, so the costs are 5, 10, 15, 20, 20.
Also fixes the way Kuei-jin max HP is calculated, because this didn't properly take both physique and dharma into account.
The benefits of Dharma levels 2-4 are limited to +25 HP, and 20XP is just a crazy cost for that at the moment - Physique does that and more! Only 5 and 6 provide any other benefit, those being other ways to draw chi (very useful) and an increase to your maximum resources.
<details>
I have 935 XP.
I now have 925 XP.
The above image was taken with 6 physique and Dharma 3.
This one was taken with 5 physique and Dharma 6.
</details>
:cl:
balance: kuei-jin only need …
> Makes the cost of raising your Dharma level scale with level (also, a non-critical but substantial bug fix)

- code/modules/vtmb/jobs/police.dm
This pull request simply increases the number of ghouls that can be playing the Police Officer role simultaneously from one, to two.
While there's nothing wrong with the current state of affairs (even though it is annoying when I can't play because of it), if you're going to allow one, why not two?
:cl:
add: Changes the amount of ghouls that can be police officer from one to two
/:cl:
> Changes the amount of ghouls that can be playing the Police Officer role simultaneously from one to two.

- code/modules/wod13/packadulteration.dm
Cocaine adulterated blood bags are now craftable instead of directing to a morphine pack.
Morphine adulterated packs can now be crafted with 15 morphine reagent(the same amount in the syringe)
For some bizarre reason reagents in a syringe don't count for a reagent recipe so I separated the two recipes.
Not being able to make cocaine bags due to a bug is bad.
Having to use the contraband needles for adulteration and not being able to use the morphine bottles lying around medical facilities was kind of stupid.
<details>
</details>
:cl:
add: A recipe for morphine bottle adulteration that uses morphine reagent.
fix: Cocaine blood bag recipe no longer gives morphine blood bags.
/:cl:
> Fixes cocaine adulteration and adds a recipe for morphine adulteration from reagent bottles.

- code/modules/vtmb/chi_disciplines.dm
Currently there's a slight error in the code for Hellweaving and Kiai that makes it check the caster's social stat against their own mental stat, instead of their target's. This means that a Kuei-Jin with 2 social, 1 mental could pass the check on any target, and one with equal social/mental stats or higher mental could never pass the check. This PR fixes that check by just checking the target's mental stat instead, as was presumably intended.
Gaming *your own stats* to be able to hit *literally any character* with a disruptive ability is not good balance. 
I don't have pictures, but I did test the change. It went from giving me a failure message on human NPCs when I had 6/6 social/mental, to giving me the expected success and the appropriate effect occuring.
:cl:
fix: fixed the check for …
> Makes Hellweaving and Kiai properly check target's mental stats

- code/__DEFINES/wod13/discipline.dm
- code/modules/wod13/datums/powers/discipline/__discipline_power.dm
- code/modules/wod13/datums/powers/discipline/auspex.dm
- code/modules/wod13/datums/powers/discipline/bloodheal.dm
- code/modules/wod13/datums/powers/discipline/celerity.dm
- code/modules/wod13/datums/powers/discipline/fortitude.dm
- code/modules/wod13/datums/powers/discipline/obfuscate.dm
- code/modules/wod13/datums/powers/discipline/potence.dm
Increases physical Discipline duration from 6 seconds to 10 seconds, decreases Bloodheal cooldown from 6 seconds to 5 seconds, make the Galdjum artifact increase power duration again, make Auspex and Obfuscate fully toggled without needing to spend blood as in tabletop.
Makes physical Disciplines less awful to use, fixes a bug, and also brings Auspex and Obfuscate closer to tabletop. They still need rolling, but this is a STEP.
<details>
</details>
:cl:
- Celerity, Fortitude, and Potence now last 10 seconds between spending vitae rather than 6.
- Bloodheal now has a 5 second cooldown rather than 6.
- Obfuscate and Auspex are now fully toggled and do …
> Buff Disciplines

- code/modules/wod13/datums/powers/discipline/visceratika.dm
This bounty PR reworks Armor Of Terra, making it so that, instead of making you into a statue structure, it instead turns you functionally int a statue... if that make sense.
Essentially turns you grey, mute, immobile, godmode for the duration of the ability.
It's a toggle, consuming 1 blood per minute with a maximum duration of in a statue of three minutes. enough time for help to arrive, hopefully anyways. also a cooldown between deactivation and activation of two minutes.
At the moment, gargoyles can become via viseratika 4 a statue that they cannot leave for 3 minutes, nor emote or act as said statue. This seems really half-assed, especially since it's not a toggle you can control and not all that useful.
This reworks it to be less jank, and at least adds a tiny bit more usability …
> Reworks Armor Of Terra From Gargoyle's Visceratika Discipline

- code/modules/vtmb/jobs/anarchs/baron.dm
Includes Baali, Caitiff and Banu Haqim as allowed Barons. Caitiff should be allowed to be Barons as it's the most feasible position of 'power' one could obtain, disallowing an actual Prince as I consider the one example of that, the Prince of Cairo, to be an exception, not an example. Baali could be Barons for sure and would as it helps them blend in to perform their evil acts. Banu I am unsure but since Banu are no longer whitelisted, it would be good to give them more jobs.
Include Baali, Banu Haqim and Caitiff as allowable Barons.
Allows more to be Barons if they wish and won't be stymied because of their Clan/Bloodline.
<details>
</details>
:cl: …
> Allow more Bloodlines to be Barons.

- _maps/map_files/Vampire/SanFrancisco.dmm
Two houses in Chinatown used the wrong windows, this has been fixed.
> Dwelling mapping fixes

- code/datums/chatmessage.dm
- code/datums/progressbar.dm
This attempts to fix the current client side bug where images sent to the client do not properly retain their transformation vars, so they flicker before they are "snapped" to their intended value by an animate() call.
In essence this puts dummy 1 tick animate calls while the image is being prepped and sleeps the prep for 1 tick to make sure the animation runs before the image is sent to the client. Images transformed by animate() seem to reatain their intended values client side.
> Potential icon and runechat flickering fix

- code/modules/flufftext/Hallucination.dm
Currently the hallucination value rests at 100 to 600 ticks, or 10 to 60 seconds. This means that in solo conversations, Malkavians can literally get overwhelmed by the hallucination chat spam.  I've seen chat logs with 5-10 hallucination lines between player lines. 
Some math: Assuming a 120 minute round, with the current setting, a particularly unlucky Malkavian can go through 720 events and the average oscillating somewhere around 300.
I set the setting to 1 and 3 minutes, still meaning 40-120 events in a two hour round round and additionally cut down the chance of the chat, message and sound hallucinations happening by a similar factor, meaning that the rarer ones will happen more frequently.
Ideally this result in slightly less of the "big" hallucinations happening, but not …
> Tweaks frequency/severity of Malkavian Halluciantions

- _maps/map_files/Vampire/SanFrancisco.dmm
- code/modules/wod13/delivery/delivery_datums.dm
- code/modules/wod13/delivery/delivery_objs.dm
Post implementation quick fixes: 
- Greatly extended delivery time limits
- Dispensers show more feedback when used without a key
- Added missing breakpoint to contract readout
- Contracts should now be useable from the inventory, not only by attacking oneself with them
- Makes the vending machine and water cooler in the Tower Lobby not have density since they are shifted against the wall.
> delivery quick fixes

- code/modules/wod13/delivery/delivery_objs.dm
changes attack_hand to attack_self like it should have been in the first place, no one saw this shhh
> Re-fixes looking at contracts

- code/modules/wod13/delivery/delivery_objs.dm
Someone forgot to tell the crates what dispensers they came from and the whole thing broke as a result, whoops.
- Dispensers accept the crates they spawn again.
> Ffffffixes the dispensers not taking back the packages they spawned

- code/modules/mob/living/carbon/human/examine.dm
After playing some rounds with the new tgui descriptions, I completely hate the fact that flavor text is now cut off after 100 chars in the look menu. It seems like throwing it into a separate popup all but guarantees that no one reads them and that's not the intent here I think.
As such
- The look dialog now displays the whole flavor text
- The tgui examine link appears only if the person being examined has their face obscured and/or has ooc flavor set.
This takes care of the cases where the dialog is actually useful, but keeps the descriptions where they imo belong.
Tested locally, all was fine.
> Puts full flavor text back in the look results

- _maps/map_files/Vampire/SanFrancisco.dmm
- code/game/objects/structures/window.dm
- code/game/objects/structures/window_frames/frames/window_frame_variants.dm
- code/game/objects/structures/window_frames/window_frame.dm
This is a follow up to https://github.com/WorldOfDarknessXIII/World-of-Darkness-13/pull/979
This moves curtain spawning code one level higher to accommodate reinforced windows, creates an in use contingency for the repair kits...
...and then replaces all turfs on the map that had windows into the new structures. Every single one.
Tested locally, everything seemed to be in order after a walk through. New functionality seems to be performing as expected.
> The Window Patch - Stage 2

- code/modules/wod13/structures/doors/vampdoor.dm
Small whoopsie, doors need to be opened then closed again to be layered properly and dont draw under mobs.
This fixes that :U
> Fixes layering of repaired doors 

- code/modules/hydroponics/grown/flowers.dm
SOMEONE broke the pathing in the examine hooks. If only we had a way of knowing who. I guess we will never know!
- Fixes Sunflowers, Fraxinella, Moonflowers and Forget Me Nots not showing proper prompts for flower language users.
> Fixes multiple flowers not showing information for flower language traits

- _maps/map_files/Vampire/SanFrancisco.dmm
- code/game/machinery/doors/poddoor.dm
Keys can now be used to open/close garage shutters when used directly on them. This makes it so authorized users don't have to go look for the damn button, then go around to the car since they cant use the closed shutters now.
Also, the Camarilla limo is now only openable by those with Theater access, so the Sheriff, Seneschal and Prince. No more joyriding.
Tested locally, everything checked out.
> Makes keys work on garage doors, changes Camarilla limo access

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/species_types/humans.dm
- code/modules/vtmb/ghoul_species.dm
- code/modules/vtmb/kindred_species.dm
- code/modules/vtmb/kuei_jin.dm
- code/modules/vtmb/werewolf_species.dm
Random touchups that don't fit anywhere else:
- Adjusts padding on about me screen to compensate for smaller resolution displays.
- Characters with a neutral gender are now identified as a person, not male.
Tested locally etc etc.
> Adusts padding on about me screen and fixes neutral gender display

- code/modules/vtmb/gamemodes/masquerade.dm
Currently one Sabbatite or Masqu breaker joining in low pop can literally swat the entire server. Conversely, on high pop this makes those decreases next to unnoticeable. 
Replaced with a flat 100 per masqu breacher and sabatitie, to be revised should we have higher numbers again.
- Each Sabbatite and Masquerade Breacher now reduces the global masquerade by a flat 100 instead of very odd values scaled by population. No more singlehandedly tanking the masquerade to 0.
> Removes pop scaling from global masquerade calculations

- code/modules/client/preferences.dm
- code/modules/mob/dead/new_player/preferences_setup.dm
This is particularly annoying during local testing as it halts the server starting up not once but twice. Say someone pushes F5 and walks away for a while forgetting these happened. Cough.
Also, runtimes are bad.
-Fixes the two runtimes that show up (and stop loading dead in its tracks, waiting for user input) whenever a Guest user logs into a local instance.
> Fixes the 2 runtimes that show up on guest login.

- code/modules/vtmb/werewolf/gifts.dm
Razor claws adds 3 aggravated damage when you're in Crinos/Lupus/Hispo, and on ending, it sets **toxin** damage to 0. This is obviously a bug. It should be setting the aggravated damage it applied to 0. This will also interfere with Venom Claws and if you Razor Claws ends while you have Venom Claws active, your toxin damage is set to 0.
Abilities should remove what they add when they end, instead of removing other things.
<details>
</details>
:cl:
fix: Razor claws now correctly removes its aggs damage when in Crinos/Lupus/Hispo
/:cl:
> Makes Razor Claws correctly remove Aggravated in Inhuman Forms
